/* ============================================================
   ARCANUM — Instrumento de leitura de Tarô (RWS)
   Bilíngue PT-BR / EN. Campos codificados "pt|en".
   ============================================================ */

const L = (s, lang) => {
  if (!s) return "";
  const p = String(s).split("|");
  return lang === "en" ? (p[1] || p[0]) : p[0];
};
const LA = (arr, lang) => (arr || []).map((s) => L(s, lang));

// arc: "M"=Maior, w=Paus/Wands, c=Copas/Cups, s=Espadas/Swords, p=Ouros/Pentacles
// line: linha de Pollack (0 = O Louco; 1,2,3 = as três linhas de sete)
// portal: carta-portal (Pollack)

const MAJORS = [
  { id:"M0", n:0, arc:"M", line:0, name:"O Louco|The Fool", el:"Ar|Air", as:"Urano|Uranus",
    col:["amarelo|yellow","branco|white","vermelho|red"],
    sym:["beira do penhasco|cliff edge","cão branco|white dog","rosa branca|white rose","trouxa no bastão|bundle on a staff","sol alto|high sun"],
    up:["começo|beginning","salto de fé|leap of faith","potencial puro|pure potential","inocência|innocence","liberdade|freedom"],
    rev:["salto adiado|postponed leap","imprudência|recklessness","medo do vazio|fear of the void"],
    fn:"Abre e encerra o ciclo: energia sem forma, anterior e posterior a toda a jornada.|Opens and closes the cycle: formless energy, prior and posterior to the whole journey.",
    al:"O penhasco existe. A carta não promete rede — promete movimento.|The cliff is real. The card promises no net — it promises movement." },
  { id:"M1", n:1, arc:"M", line:1, name:"O Mago|The Magician", el:"Ar|Air", as:"Mercúrio|Mercury",
    col:["vermelho|red","branco|white","amarelo|yellow"],
    sym:["lemniscata|lemniscate","quatro naipes na mesa|four suits on the table","braço acima, braço abaixo|one arm up, one arm down","lírios e rosas|lilies and roses"],
    up:["vontade|will","manifestação|manifestation","recurso disponível|available resource","foco|focus","habilidade|skill"],
    rev:["talento não canalizado|uncanalized talent","manipulação|manipulation","dispersão|scattering"],
    fn:"Primeiro polo da dualidade: a consciência ativa que dirige a energia para fora.|First pole of duality: active consciousness directing energy outward.",
    al:"Ter os quatro naipes na mesa não é o mesmo que usá-los.|Having the four suits on the table is not the same as using them." },
  { id:"M2", n:2, arc:"M", line:1, name:"A Sacerdotisa|The High Priestess", el:"Água|Water", as:"Lua|Moon",
    col:["azul|blue","branco|white","preto|black"],
    sym:["véu de romãs|veil of pomegranates","pilares B e J|pillars B and J","lua crescente aos pés|crescent moon at her feet","rolo TORA|TORA scroll"],
    up:["saber latente|latent knowing","intuição|intuition","silêncio|silence","o que ainda não se formulou|what has not yet been formulated"],
    rev:["intuição abafada|muffled intuition","segredo que pesa|secret that weighs","desconexão do interior|inner disconnection"],
    fn:"Segundo polo: consciência passiva e receptiva. Guarda o que o Mago ainda não sabe nomear.|Second pole: passive, receptive consciousness. Keeps what the Magician cannot yet name.",
    al:"A resposta existe e ainda não está pronta para ser dita.|The answer exists and is not yet ready to be spoken." },
  { id:"M3", n:3, arc:"M", line:1, name:"A Imperatriz|The Empress", el:"Terra|Earth", as:"Vênus|Venus",
    col:["verde|green","dourado|gold","vermelho|red"],
    sym:["campo de trigo|wheat field","coroa de doze estrelas|crown of twelve stars","escudo de Vênus|Venus shield","cachoeira|waterfall","almofadas|cushions"],
    up:["abundância|abundance","fertilidade|fertility","sensualidade|sensuality","criação|creation","cuidado|nurture"],
    rev:["criatividade estagnada|stalled creativity","excesso de cuidado com o outro|over-nurturing others","desconexão do corpo|disconnection from the body"],
    fn:"A matriz que dá forma material ao que a Sacerdotisa guarda em potência.|The matrix that gives material form to what the High Priestess holds in potential.",
    al:"Abundância exige colheita. O trigo maduro apodrece se ninguém corta.|Abundance requires harvest. Ripe wheat rots if no one cuts it." },
  { id:"M4", n:4, arc:"M", line:1, name:"O Imperador|The Emperor", el:"Fogo|Fire", as:"Áries|Aries",
    col:["vermelho|red","laranja|orange","cinza|grey"],
    sym:["trono de pedra|stone throne","cabeças de carneiro|ram heads","ankh e globo|ankh and orb","montanhas áridas|barren mountains","armadura|armour"],
    up:["estrutura|structure","autoridade|authority","limite|boundary","ordem|order","disciplina|discipline"],
    rev:["rigidez|rigidity","autoridade contestada|contested authority","estrutura que aprisiona|structure that imprisons"],
    fn:"Impõe forma e lei ao mundo exterior; a estrutura sem a qual a Imperatriz se dissolve.|Imposes form and law on the outer world; the structure without which the Empress dissolves.",
    al:"As montanhas atrás dele não têm vegetação. Ordem tem custo.|The mountains behind him carry no vegetation. Order has a cost." },
  { id:"M5", n:5, arc:"M", line:1, name:"O Hierofante|The Hierophant", el:"Terra|Earth", as:"Touro|Taurus",
    col:["vermelho|red","cinza|grey","branco|white"],
    sym:["tríplice coroa|triple crown","dois acólitos|two acolytes","chaves cruzadas|crossed keys","pilares cinzentos|grey pillars","gesto de bênção|blessing gesture"],
    up:["tradição|tradition","ensino|teaching","instituição|institution","iniciação formal|formal initiation","valores herdados|inherited values"],
    rev:["dogma questionado|dogma questioned","busca de caminho próprio|search for one's own path","ruptura com a instituição|break with the institution"],
    fn:"A ponte entre o indivíduo e o coletivo: o conhecimento transmitido, não descoberto.|The bridge between individual and collective: knowledge transmitted, not discovered.",
    al:"A doutrina que protege é a mesma que limita.|The doctrine that protects is the one that limits." },
  { id:"M6", n:6, arc:"M", line:1, name:"Os Amantes|The Lovers", el:"Ar|Air", as:"Gêmeos|Gemini",
    col:["azul|blue","amarelo|yellow","verde|green"],
    sym:["anjo Rafael|angel Raphael","árvore de chamas|tree of flames","árvore com serpente|tree with serpent","montanha ao centro|mountain at centre","nudez|nakedness"],
    up:["escolha|choice","união|union","valores em jogo|values at stake","atração|attraction","alinhamento|alignment"],
    rev:["escolha evitada|avoided choice","desalinhamento de valores|misaligned values","vínculo em desequilíbrio|imbalanced bond"],
    fn:"O primeiro ato genuíno de decisão consciente: escolher é abrir mão.|The first genuine act of conscious decision: to choose is to relinquish.",
    al:"As figuras olham para o anjo, não uma para a outra. A escolha é acima do desejo.|The figures look at the angel, not at each other. The choice sits above desire." },
  { id:"M7", n:7, arc:"M", line:1, name:"O Carro|The Chariot", el:"Água|Water", as:"Câncer|Cancer",
    col:["azul|blue","cinza|grey","amarelo|yellow"],
    sym:["duas esfinges preta e branca|black and white sphinxes","dossel de estrelas|canopy of stars","ausência de rédeas|absence of reins","cidade atrás|city behind","escudo alado|winged shield"],
    up:["vitória pela vontade|victory by will","direção|direction","controle de forças opostas|control of opposing forces","partida|departure"],
    rev:["forças em disputa|forces in dispute","avanço sem direção|advance without direction","vontade travada|stalled will"],
    fn:"Encerra a Linha 1: o ego maduro, capaz de dirigir o mundo exterior. Ainda não olhou para dentro.|Closes Line 1: the mature ego, able to steer the outer world. It has not yet looked inward.",
    al:"Não há rédeas. O controle é psíquico e pode ceder a qualquer momento.|There are no reins. Control is psychic and can give way at any moment." },
  { id:"M8", n:8, arc:"M", line:2, name:"A Força|Strength", el:"Fogo|Fire", as:"Leão|Leo",
    col:["branco|white","amarelo|yellow","laranja|orange"],
    sym:["lemniscata|lemniscate","leão dócil|docile lion","guirlanda de flores|garland of flowers","mãos na mandíbula|hands on the jaw","veste branca|white robe"],
    up:["coragem serena|quiet courage","domínio do instinto|mastery of instinct","paciência|patience","persuasão suave|gentle persuasion"],
    rev:["força bruta|brute force","instinto reprimido|repressed instinct","autoconfiança abalada|shaken self-trust"],
    fn:"Abre a Linha 2: a mesma potência do Carro, agora voltada para dentro, sem violência.|Opens Line 2: the Chariot's same power, now turned inward, without violence.",
    al:"O leão não foi morto nem domado — foi convencido. Isso é reversível.|The lion was neither killed nor tamed — it was persuaded. That is reversible." },
  { id:"M9", n:9, arc:"M", line:2, name:"O Eremita|The Hermit", el:"Terra|Earth", as:"Virgem|Virgo",
    col:["cinza|grey","amarelo|yellow","branco|white"],
    sym:["lanterna com estrela de seis pontas|lantern with six-pointed star","cajado|staff","cume nevado|snowy peak","capuz|hood","solidão|solitude"],
    up:["retiro|retreat","busca interior|inner search","discernimento|discernment","orientação|guidance","solidão escolhida|chosen solitude"],
    rev:["isolamento|isolation","recusa em olhar para dentro|refusal to look within","conselho ignorado|advice ignored"],
    fn:"O ego se afasta do mundo para encontrar a luz que já carregava.|The ego withdraws from the world to find the light it already carried.",
    al:"Ele ilumina o próprio próximo passo, não o caminho inteiro.|He lights his own next step, not the whole road." },
  { id:"M10", n:10, arc:"M", line:2, name:"A Roda da Fortuna|Wheel of Fortune", el:"Fogo|Fire", as:"Júpiter|Jupiter",
    col:["amarelo|yellow","azul|blue","laranja|orange"],
    sym:["TARO/ROTA|TARO/ROTA","esfinge, Anúbis, serpente|sphinx, Anubis, serpent","quatro criaturas aladas com livros|four winged creatures with books","letras hebraicas|Hebrew letters"],
    up:["ciclo|cycle","virada|turning point","destino em movimento|destiny in motion","sincronicidade|synchronicity","sorte|fortune"],
    rev:["resistência ao ciclo|resistance to the cycle","atraso|delay","repetição do padrão|pattern repetition"],
    fn:"Centro da Linha 2: mostra que o padrão pessoal está inserido num movimento maior.|Centre of Line 2: shows the personal pattern set inside a larger movement.",
    al:"A roda gira quer você esteja pronto ou não.|The wheel turns whether you are ready or not." },
  { id:"M11", n:11, arc:"M", line:2, name:"A Justiça|Justice", el:"Ar|Air", as:"Libra|Libra",
    col:["vermelho|red","amarelo|yellow","roxo|purple"],
    sym:["espada erguida|raised sword","balança|scales","véu roxo|purple veil","coroa quadrada|square crown","pé aparecendo|foot emerging"],
    up:["equilíbrio|balance","causa e consequência|cause and consequence","verdade|truth","decisão justa|fair decision","responsabilidade|accountability"],
    rev:["desequilíbrio|imbalance","recusa da responsabilidade|refusal of accountability","julgamento parcial|partial judgement"],
    fn:"A avaliação honesta do que foi feito — condição para seguir na Linha 2.|The honest reckoning of what has been done — the condition for continuing along Line 2.",
    al:"A espada aponta para cima, não para o outro. O julgamento é interno.|The sword points up, not at another. The judgement is internal." },
  { id:"M12", n:12, arc:"M", line:2, name:"O Enforcado|The Hanged Man", el:"Água|Water", as:"Netuno|Neptune",
    col:["azul|blue","vermelho|red","amarelo|yellow"],
    sym:["árvore em T (Tau)|T-shaped tree (Tau)","auréola|halo","perna em quatro|leg forming a four","serenidade no rosto|serene face","suspensão voluntária|voluntary suspension"],
    up:["suspensão|suspension","inversão de perspectiva|reversal of perspective","entrega|surrender","pausa fértil|fertile pause","sacrifício|sacrifice"],
    rev:["pausa que virou paralisia|pause turned paralysis","resistência à entrega|resistance to surrender","martírio inútil|useless martyrdom"],
    fn:"A rendição consciente que precede a transformação. Nada avança até o ponto de vista mudar.|The conscious surrender preceding transformation. Nothing moves until the viewpoint changes.",
    al:"A corda está no tornozelo, não no pescoço. Você pode descer — e escolhe não descer.|The rope is at the ankle, not the neck. You can come down — and choose not to." },
  { id:"M13", n:13, arc:"M", line:2, name:"A Morte|Death", el:"Água|Water", as:"Escorpião|Scorpio",
    col:["preto|black","branco|white","vermelho|red"],
    sym:["armadura negra|black armour","rosa branca de cinco pétalas|five-petalled white rose","rio ao fundo|river in the background","sol entre torres|sun between towers","bispo, mulher e criança|bishop, woman and child"],
    up:["fim necessário|necessary ending","transformação|transformation","corte|cut","liberação|release","passagem|passage"],
    rev:["fim adiado|postponed ending","apego ao que morreu|clinging to what has died","transformação bloqueada|blocked transformation"],
    fn:"Não é morte física: é a dissolução do ego construído na Linha 1.|Not physical death: the dissolution of the ego built in Line 1.",
    al:"O sol nasce entre as torres. Mas a criança é a única que olha direto para o cavaleiro.|The sun rises between the towers. Yet the child is the only one looking straight at the rider." },
  { id:"M14", n:14, arc:"M", line:2, name:"A Temperança|Temperance", el:"Fogo|Fire", as:"Sagitário|Sagittarius",
    col:["branco|white","azul|blue","amarelo|yellow"],
    sym:["um pé na água, um em terra|one foot in water, one on land","dois cálices|two cups","triângulo no peito|triangle on the chest","íris|irises","caminho para a coroa|path to the crown"],
    up:["síntese|synthesis","moderação|moderation","cura lenta|slow healing","fluxo|flow","alquimia|alchemy"],
    rev:["desequilíbrio|imbalance","excesso|excess","mistura mal feita|badly made blend"],
    fn:"Fecha a Linha 2: integra os opostos encontrados no descenso interior.|Closes Line 2: integrates the opposites met in the inner descent.",
    al:"A água passa entre os cálices num ângulo impossível. A cura não obedece à física do ego.|The water passes between cups at an impossible angle. Healing does not obey the ego's physics." },
  { id:"M15", n:15, arc:"M", line:3, name:"O Diabo|The Devil", el:"Terra|Earth", as:"Capricórnio|Capricorn",
    col:["preto|black","vermelho|red","carne|flesh"],
    sym:["correntes frouxas|loose chains","tocha invertida|inverted torch","pedestal semicúbico|half-cube pedestal","chifres e caudas nos humanos|horns and tails on the humans","pentagrama invertido|inverted pentagram"],
    up:["apego|attachment","padrão compulsivo|compulsive pattern","materialismo|materialism","sombra|shadow","prisão consentida|consented prison"],
    rev:["consciência da corrente|awareness of the chain","início da libertação|beginning of release","confronto com a sombra|confronting the shadow"],
    fn:"Abre a Linha 3: o encontro com a força arquetípica que o ego não controla.|Opens Line 3: the encounter with archetypal force the ego cannot control.",
    al:"As correntes cabem sobre as cabeças. Ninguém as tirou.|The chains fit over the heads. No one has removed them." },
  { id:"M16", n:16, arc:"M", line:3, name:"A Torre|The Tower", el:"Fogo|Fire", as:"Marte|Mars",
    col:["cinza|grey","vermelho|red","amarelo|yellow"],
    sym:["raio|lightning bolt","coroa expelida|crown blasted off","duas figuras caindo|two falling figures","chamas em forma de yod|yod-shaped flames","rocha nua|bare rock"],
    up:["ruptura|rupture","revelação súbita|sudden revelation","colapso da falsa estrutura|collapse of the false structure","choque|shock"],
    rev:["colapso evitado|averted collapse","ruína contida|contained ruin","medo do desmoronamento|fear of collapse"],
    fn:"Destrói a estrutura do Imperador quando ela deixou de servir à verdade.|Destroys the Emperor's structure once it has ceased to serve truth.",
    al:"A coroa cai primeiro. O que rui é o que você chamava de identidade.|The crown falls first. What collapses is what you called identity." },
  { id:"M17", n:17, arc:"M", line:3, name:"A Estrela|The Star", el:"Ar|Air", as:"Aquário|Aquarius",
    col:["amarelo|yellow","azul|blue","verde|green"],
    sym:["oito estrelas|eight stars","dois jarros|two jugs","um pé na água, um em terra|one foot in water, one on land","íbis na árvore|ibis in the tree","nudez sem vergonha|shameless nakedness"],
    up:["esperança|hope","renovação|renewal","serenidade|serenity","inspiração|inspiration","fé recuperada|restored faith"],
    rev:["fé abalada|shaken faith","desânimo|discouragement","esperança adiada|deferred hope"],
    fn:"A calma que segue a Torre: sem defesas, sem roupa, sem mentira.|The calm following the Tower: no defences, no clothing, no lie.",
    al:"Ela derrama água de volta no lago. Nada aqui é acumulação.|She pours water back into the pool. Nothing here is accumulation." },
  { id:"M18", n:18, arc:"M", line:3, name:"A Lua|The Moon", el:"Água|Water", as:"Peixes|Pisces",
    col:["azul|blue","amarelo|yellow","cinza|grey"],
    sym:["cão e lobo|dog and wolf","lagostim saindo da água|crayfish emerging from water","duas torres|two towers","caminho ao longe|distant path","gotas de orvalho (yods)|dew drops (yods)"],
    up:["ilusão|illusion","inconsciente|the unconscious","medo difuso|diffuse fear","sonho|dream","navegação sem clareza|navigation without clarity"],
    rev:["ilusão se dissipando|illusion dissipating","medo nomeado|fear named","confusão que cede|confusion giving way"],
    fn:"A travessia do território arquetípico mais antigo, anterior à linguagem.|The crossing of the oldest archetypal territory, prior to language.",
    al:"O caminho existe e some entre as torres. Não peça mapa aqui.|The path exists and vanishes between the towers. Do not ask for a map here." },
  { id:"M19", n:19, arc:"M", line:3, name:"O Sol|The Sun", el:"Fogo|Fire", as:"Sol|Sun",
    col:["amarelo|yellow","laranja|orange","vermelho|red"],
    sym:["criança em cavalo branco|child on a white horse","girassóis|sunflowers","estandarte vermelho|red banner","muro|wall","raios retos e ondulados|straight and wavy rays"],
    up:["clareza|clarity","vitalidade|vitality","alegria|joy","sucesso visível|visible success","verdade exposta|exposed truth"],
    rev:["alegria contida|contained joy","clareza parcial|partial clarity","brilho adiado|delayed shine"],
    fn:"A consciência que retorna do mundo da Lua sem perder a inocência.|Consciousness returning from the Moon's world without losing innocence.",
    al:"A criança está do lado de fora do muro. O jardim ficou para trás.|The child is outside the wall. The garden is behind." },
  { id:"M20", n:20, arc:"M", line:3, name:"O Julgamento|Judgement", el:"Fogo|Fire", as:"Plutão|Pluto",
    col:["cinza|grey","branco|white","vermelho|red"],
    sym:["anjo Gabriel|angel Gabriel","trombeta com estandarte|trumpet with banner","figuras erguendo-se dos caixões|figures rising from coffins","montanhas ao fundo|mountains behind","braços abertos|open arms"],
    up:["chamado|calling","avaliação|reckoning","despertar|awakening","renascimento|rebirth","perdão|absolution"],
    rev:["chamado ignorado|calling ignored","autocrítica severa|harsh self-judgement","despertar adiado|postponed awakening"],
    fn:"O chamado que reorganiza a vida inteira em torno de um propósito reconhecido.|The call that reorganises an entire life around a recognised purpose.",
    al:"As figuras não pedem para se levantar. Elas ouvem e se levantam.|The figures do not ask to rise. They hear, and rise." },
  { id:"M21", n:21, arc:"M", line:3, name:"O Mundo|The World", el:"Terra|Earth", as:"Saturno|Saturn",
    col:["verde|green","roxo|purple","azul|blue"],
    sym:["guirlanda oval|oval wreath","quatro criaturas nos cantos|four creatures at the corners","duas varinhas|two wands","echarpe roxa|purple scarf","pernas cruzadas como o Enforcado|legs crossed like the Hanged Man"],
    up:["completude|completion","integração|integration","realização|fulfilment","fechamento de ciclo|cycle closing","pertencimento|belonging"],
    rev:["ciclo quase fechado|cycle nearly closed","conclusão adiada|deferred conclusion","falta um último passo|one last step missing"],
    fn:"Fecha a Linha 3 e o Padrão dos Quatro: a unidade que o Louco carregava como potência.|Closes Line 3 and the Pattern of Four: the unity the Fool carried as potential.",
    al:"A guirlanda é oval, não circular. Mesmo o fim tem uma abertura.|The wreath is oval, not circular. Even the ending has an opening." },
];

const WANDS = [
  { id:"w1", n:1, arc:"w", name:"Ás de Paus|Ace of Wands", as:"Raiz do Fogo|Root of Fire",
    col:["verde|green","cinza|grey","amarelo|yellow"],
    sym:["mão saindo da nuvem|hand from a cloud","bastão brotando folhas|wand sprouting leaves","castelo ao longe|distant castle","yods caindo|falling yods"],
    up:["impulso novo|new impulse","faísca|spark","oportunidade de ação|opportunity for action","desejo|desire"],
    rev:["impulso contido|contained impulse","início adiado|delayed start","energia sem canal|energy without a channel"],
    fn:"A semente pura do elemento Fogo: potencial de movimento antes de qualquer forma.|The pure seed of Fire: potential for movement before any form.",
    al:"O bastão é oferecido, não entregue. Alguém precisa segurá-lo.|The wand is offered, not handed over. Someone must grasp it." },
  { id:"w2", n:2, arc:"w", name:"Dois de Paus|Two of Wands", as:"Marte em Áries|Mars in Aries",
    col:["laranja|orange","cinza|grey","vermelho|red"],
    sym:["globo na mão|globe in hand","um bastão preso à muralha|one wand fixed to the wall","rosas e lírios cruzados|crossed roses and lilies","vista do parapeito|view from the parapet"],
    up:["planejamento|planning","horizonte|horizon","decisão de expandir|decision to expand","poder pessoal|personal power"],
    rev:["medo do desconhecido|fear of the unknown","plano engavetado|shelved plan","conforto que prende|comfort that holds you"],
    fn:"O momento anterior à partida: o mundo já cabe na mão, mas o pé ainda não saiu.|The moment before departure: the world already fits in the hand, but the foot has not moved.",
    al:"Um bastão está preso à parede. Parte de você já decidiu ficar.|One wand is fixed to the wall. Part of you has already decided to stay." },
  { id:"w3", n:3, arc:"w", portal:true, name:"Três de Paus|Three of Wands", as:"Sol em Áries|Sun in Aries",
    col:["amarelo|yellow","laranja|orange","vermelho|red"],
    sym:["figura de costas|figure seen from behind","navios no mar|ships at sea","três bastões plantados|three planted wands","penhasco alto|high cliff"],
    up:["expansão|expansion","espera ativa|active waiting","visão de longo alcance|long-range vision","empreendimento em curso|venture underway"],
    rev:["retorno demorado|delayed return","planos revistos|revised plans","horizonte estreitado|narrowed horizon"],
    fn:"CARTA-PORTAL: a figura de costas convida quem lê a olhar para o mesmo mar. Abre experiência arquetípica além do sentido literal.|PORTAL CARD: the figure's back invites the reader to look at the same sea. Opens archetypal experience beyond literal meaning.",
    al:"Os navios já partiram. O que você vê não está mais sob seu controle.|The ships have sailed. What you see is no longer under your control." },
  { id:"w4", n:4, arc:"w", name:"Quatro de Paus|Four of Wands", as:"Vênus em Áries|Venus in Aries",
    col:["amarelo|yellow","verde|green","azul|blue"],
    sym:["dossel de flores|canopy of flowers","duas figuras com buquês|two figures with bouquets","castelo|castle","ponte e fosso|bridge and moat"],
    up:["celebração|celebration","chegada|arrival","lar|home","estabilidade conquistada|earned stability","marco|milestone"],
    rev:["celebração adiada|postponed celebration","instabilidade doméstica|domestic instability","transição sem marco|transition without a milestone"],
    fn:"O primeiro repouso estável do Fogo: fundação erguida, não fim de jornada.|Fire's first stable rest: a foundation raised, not a journey's end.",
    al:"O dossel tem quatro pilares e nenhuma parede. É abrigo, não fortaleza.|The canopy has four pillars and no walls. It is shelter, not fortress." },
  { id:"w5", n:5, arc:"w", name:"Cinco de Paus|Five of Wands", as:"Saturno em Leão|Saturn in Leo",
    col:["verde|green","amarelo|yellow","vermelho|red"],
    sym:["cinco jovens|five youths","bastões sem alvo|wands with no target","roupas de cores diferentes|clothes of different colours","terreno irregular|uneven ground"],
    up:["conflito|conflict","competição|competition","ruído de vozes|noise of voices","teste|testing"],
    rev:["conflito interno|internal conflict","evitação do embate|avoidance of confrontation","trégua|truce"],
    fn:"A fricção necessária quando várias vontades ocupam o mesmo espaço.|The necessary friction when several wills occupy the same space.",
    al:"Ninguém está ferido. É ensaio, e ainda assim consome sua energia.|No one is injured. It is rehearsal, and it still drains you." },
  { id:"w6", n:6, arc:"w", name:"Seis de Paus|Six of Wands", as:"Júpiter em Leão|Jupiter in Leo",
    col:["vermelho|red","verde|green","branco|white"],
    sym:["coroa de louros|laurel wreath","cavalo branco encoberto|draped white horse","multidão ao redor|surrounding crowd","bastão com guirlanda|wand with a garland"],
    up:["reconhecimento|recognition","vitória pública|public victory","confiança|confidence","boa notícia|good news"],
    rev:["reconhecimento negado|withheld recognition","vitória sem público|victory without an audience","confiança abalada|shaken confidence"],
    fn:"O retorno triunfal: o Fogo validado pelo olhar coletivo.|The triumphal return: Fire validated by the collective gaze.",
    al:"A multidão sustenta o triunfo. Se ela dispersa, o que resta?|The crowd sustains the triumph. If it disperses, what remains?" },
  { id:"w7", n:7, arc:"w", name:"Sete de Paus|Seven of Wands", as:"Marte em Leão|Mars in Leo",
    col:["verde|green","amarelo|yellow","azul|blue"],
    sym:["terreno elevado|high ground","seis bastões vindos de baixo|six wands from below","calçados diferentes|mismatched shoes","postura defensiva|defensive stance"],
    up:["defesa de posição|defence of position","perseverança|perseverance","coragem sob pressão|courage under pressure","limite afirmado|boundary asserted"],
    rev:["exaustão da defesa|defence exhaustion","posição cedida|position surrendered","luta desnecessária|unnecessary fight"],
    fn:"Manter o que foi conquistado no Seis exige mais energia do que conquistar.|Holding what the Six won costs more energy than the winning did.",
    al:"Os sapatos não combinam. Você entrou nessa briga sem se preparar.|The shoes do not match. You entered this fight unprepared." },
  { id:"w8", n:8, arc:"w", name:"Oito de Paus|Eight of Wands", as:"Mercúrio em Sagitário|Mercury in Sagittarius",
    col:["amarelo|yellow","verde|green","azul|blue"],
    sym:["oito bastões em voo|eight wands in flight","nenhuma figura humana|no human figure","rio e colina|river and hill","céu limpo|clear sky"],
    up:["velocidade|speed","mensagem a caminho|message in transit","acontecimentos rápidos|rapid events","alinhamento|alignment"],
    rev:["atraso|delay","mensagem retida|withheld message","ritmo desacelerado|slowed pace"],
    fn:"Movimento puro sem agente: a única carta do baralho sem figura nem cenário ocupado.|Pure movement without an agent: the only card with neither figure nor occupied scene.",
    al:"Os bastões ainda estão no ar. Nada aterrissou.|The wands are still in the air. Nothing has landed." },
  { id:"w9", n:9, arc:"w", name:"Nove de Paus|Nine of Wands", as:"Lua em Sagitário|Moon in Sagittarius",
    col:["amarelo|yellow","cinza|grey","laranja|orange"],
    sym:["cabeça enfaixada|bandaged head","oito bastões em fila atrás|eight wands lined up behind","olhar de esguelha|sideways glance","apoio no bastão|leaning on a wand"],
    up:["resiliência|resilience","vigilância|vigilance","penúltimo esforço|penultimate effort","cicatriz|scar"],
    rev:["defesa paranoica|paranoid defence","exaustão|exhaustion","muro desnecessário|unnecessary wall"],
    fn:"A memória das batalhas anteriores tornada postura corporal.|The memory of past battles turned into bodily posture.",
    al:"A cerca atrás dele já está de pé. Ele defende algo que já está seguro.|The fence behind him already stands. He is defending something already safe." },
  { id:"w10", n:10, arc:"w", name:"Dez de Paus|Ten of Wands", as:"Saturno em Sagitário|Saturn in Sagittarius",
    col:["amarelo|yellow","verde|green","marrom|brown"],
    sym:["dez bastões em braçada|ten wands in an armful","rosto oculto pela carga|face hidden by the load","aldeia à frente|village ahead","tronco curvado|bent trunk"],
    up:["sobrecarga|overload","responsabilidade acumulada|accumulated responsibility","último trecho|final stretch","peso do sucesso|weight of success"],
    rev:["carga sendo largada|load being set down","delegação|delegation","recusa do peso|refusal of the burden"],
    fn:"O Fogo levado ao extremo: a força que criou agora esmaga quem criou.|Fire at its extreme: the force that created now crushes its creator.",
    al:"Os bastões tapam a visão. A aldeia está perto e ele não a vê.|The wands block his sight. The village is near and he cannot see it." },
  { id:"wP", n:11, arc:"w", name:"Valete de Paus|Page of Wands", as:"Terra do Fogo|Earth of Fire",
    col:["laranja|orange","amarelo|yellow","vermelho|red"],
    sym:["salamandras na túnica|salamanders on the tunic","pena vermelha|red feather","deserto e pirâmides|desert and pyramids","olhar para o topo do bastão|gaze at the wand's tip"],
    up:["entusiasmo iniciante|beginner's enthusiasm","notícia inspiradora|inspiring news","curiosidade|curiosity","exploração|exploration"],
    rev:["entusiasmo sem direção|enthusiasm without direction","notícia frustrada|frustrated news","impaciência|impatience"],
    fn:"O elemento Terra dentro do Fogo: a ideia ainda inexperiente que quer virar prática.|Earth within Fire: the still-inexperienced idea seeking practice.",
    al:"As salamandras da túnica ainda estão com a cauda aberta — incompletas.|The salamanders on the tunic still have open tails — incomplete." },
  { id:"wN", n:12, arc:"w", name:"Cavaleiro de Paus|Knight of Wands", as:"Ar do Fogo|Air of Fire",
    col:["amarelo|yellow","laranja|orange","vermelho|red"],
    sym:["cavalo empinado|rearing horse","armadura com salamandras|armour with salamanders","pirâmides|pyramids","pena flutuando|floating plume"],
    up:["ação impetuosa|impetuous action","paixão|passion","partida súbita|sudden departure","carisma|charisma"],
    rev:["impulsividade|impulsiveness","projeto abandonado|abandoned project","pressa que custa caro|haste with a high price"],
    fn:"O Ar dentro do Fogo: a ação que se acende rápido e nem sempre sustenta.|Air within Fire: action that ignites fast and does not always sustain.",
    al:"O cavalo empina — ele não está avançando ainda.|The horse rears — he is not advancing yet." },
  { id:"wQ", n:13, arc:"w", name:"Rainha de Paus|Queen of Wands", as:"Água do Fogo|Water of Fire",
    col:["amarelo|yellow","laranja|orange","preto|black"],
    sym:["girassol|sunflower","gato preto aos pés|black cat at her feet","leões no trono|lions on the throne","postura frontal e aberta|open frontal posture"],
    up:["calor pessoal|personal warmth","autoconfiança|self-assurance","magnetismo|magnetism","liderança acolhedora|welcoming leadership"],
    rev:["autoconfiança abalada|shaken self-assurance","ciúme|jealousy","calor retirado|warmth withdrawn"],
    fn:"A Água dentro do Fogo: a paixão que aprendeu a se sustentar sem se consumir.|Water within Fire: passion that has learned to sustain itself without burning out.",
    al:"O gato preto olha para fora da carta. Ela vê o que você ainda não vê.|The black cat looks out of the card. She sees what you do not yet see." },
  { id:"wK", n:14, arc:"w", name:"Rei de Paus|King of Wands", as:"Fogo do Fogo|Fire of Fire",
    col:["laranja|orange","amarelo|yellow","verde|green"],
    sym:["leões e salamandras no trono|lions and salamanders on the throne","lagarto pequeno ao lado|small lizard beside him","postura de perfil|profile posture","coroa de chamas|crown of flames"],
    up:["visão empreendedora|entrepreneurial vision","autoridade natural|natural authority","ousadia madura|mature boldness","inspiração de outros|inspiring others"],
    rev:["autoritarismo|authoritarianism","visão imposta|imposed vision","impaciência com o processo|impatience with process"],
    fn:"O Fogo do Fogo: a vontade em estado mais puro e mais governável.|Fire of Fire: will in its purest and most governable state.",
    al:"Ele está de perfil, prestes a se levantar. Nenhum rei de Paus fica sentado por muito tempo.|He is in profile, about to rise. No King of Wands stays seated long." },
];

const CUPS = [
  { id:"c1", n:1, arc:"c", name:"Ás de Copas|Ace of Cups", as:"Raiz da Água|Root of Water",
    col:["azul|blue","branco|white","verde|green"],
    sym:["pomba com hóstia|dove with a wafer","cinco jorros de água|five streams of water","lótus no lago|lotuses on the pool","letra W ou M invertida|inverted W or M"],
    up:["abertura emocional|emotional opening","amor nascente|nascent love","graça|grace","transbordamento|overflow"],
    rev:["afeto contido|contained affection","coração fechado|closed heart","fonte bloqueada|blocked source"],
    fn:"A semente pura da Água: sentimento antes de ter objeto.|The pure seed of Water: feeling before it has an object.",
    al:"A taça já transborda. Não cabe mais — cabe distribuir.|The cup already overflows. There is no more room — only sharing." },
  { id:"c2", n:2, arc:"c", name:"Dois de Copas|Two of Cups", as:"Vênus em Câncer|Venus in Cancer",
    col:["azul|blue","vermelho|red","amarelo|yellow"],
    sym:["caduceu com cabeça de leão|caduceus with a lion's head","duas serpentes|two serpents","guirlanda na cabeça dela|garland on her head","troca de olhares|exchange of gazes"],
    up:["união|union","reciprocidade|reciprocity","atração mútua|mutual attraction","pacto|pact"],
    rev:["desequilíbrio na troca|imbalanced exchange","ruptura|rupture","vínculo por confirmar|bond awaiting confirmation"],
    fn:"O primeiro encontro real entre dois: dualidade emocional consciente.|The first real meeting between two: conscious emotional duality.",
    al:"O leão alado acima deles é a paixão. Está acima, não sob controle.|The winged lion above them is passion. It is above, not under control." },
  { id:"c3", n:3, arc:"c", name:"Três de Copas|Three of Cups", as:"Mercúrio em Câncer|Mercury in Cancer",
    col:["vermelho|red","branco|white","amarelo|yellow"],
    sym:["três mulheres dançando|three women dancing","taças erguidas|raised cups","abóbora e frutas|pumpkin and fruit","roda de mãos|circle of hands"],
    up:["celebração compartilhada|shared celebration","amizade|friendship","comunidade|community","colheita afetiva|emotional harvest"],
    rev:["excesso social|social excess","círculo desfeito|broken circle","celebração vazia|hollow celebration"],
    fn:"O sentimento que se expande do par para o grupo.|Feeling expanding from the pair into the group.",
    al:"É colheita. Toda colheita marca o fim de uma estação.|It is harvest. Every harvest marks a season's end." },
  { id:"c4", n:4, arc:"c", name:"Quatro de Copas|Four of Cups", as:"Lua em Câncer|Moon in Cancer",
    col:["verde|green","azul|blue","vermelho|red"],
    sym:["figura sob a árvore|figure under a tree","braços cruzados|crossed arms","três taças no chão|three cups on the ground","quarta taça oferecida pela nuvem|fourth cup offered from a cloud"],
    up:["apatia|apathy","insatisfação|dissatisfaction","introspecção|introspection","oferta não vista|unseen offer"],
    rev:["saindo do torpor|emerging from numbness","aceitação da oferta|accepting the offer","reengajamento|re-engagement"],
    fn:"A Água estagnada: o excesso de contemplação que se torna recusa.|Stagnant Water: contemplation in excess turning into refusal.",
    al:"A quarta taça está ali há tempo. A recusa é ativa, não passiva.|The fourth cup has been there a while. The refusal is active, not passive." },
  { id:"c5", n:5, arc:"c", name:"Cinco de Copas|Five of Cups", as:"Marte em Escorpião|Mars in Scorpio",
    col:["preto|black","cinza|grey","vermelho|red"],
    sym:["manto negro|black cloak","três taças derramadas|three spilled cups","duas taças de pé atrás|two upright cups behind","ponte e castelo|bridge and castle","rio|river"],
    up:["luto|grief","perda|loss","arrependimento|regret","foco no que se foi|focus on what is gone"],
    rev:["aceitação|acceptance","virada do olhar|turning of the gaze","luto atravessado|grief moved through"],
    fn:"A dor que estreita a visão até que só o perdido seja visível.|Pain that narrows vision until only what is lost remains visible.",
    al:"Duas taças continuam de pé, e a ponte leva a algum lugar. Nada disso está no campo de visão dele.|Two cups still stand, and the bridge leads somewhere. None of it is in his field of view." },
  { id:"c6", n:6, arc:"c", name:"Seis de Copas|Six of Cups", as:"Sol em Escorpião|Sun in Scorpio",
    col:["amarelo|yellow","verde|green","branco|white"],
    sym:["duas crianças|two children","taças com flores brancas|cups with white flowers","aldeia antiga|old village","figura se afastando ao fundo|figure walking away in the background"],
    up:["memória|memory","nostalgia|nostalgia","inocência|innocence","reencontro|reunion","doação|giving"],
    rev:["preso ao passado|stuck in the past","idealização da memória|idealised memory","retorno impossível|impossible return"],
    fn:"O tempo emocional voltado para trás: a Água guardada na lembrança.|Emotional time turned backwards: Water stored in memory.",
    al:"Alguém sai de cena ao fundo. A nostalgia sempre custa um presente.|Someone leaves the scene in the background. Nostalgia always costs a present." },
  { id:"c7", n:7, arc:"c", name:"Sete de Copas|Seven of Cups", as:"Vênus em Escorpião|Venus in Scorpio",
    col:["cinza|grey","azul|blue","amarelo|yellow"],
    sym:["silhueta de costas|silhouette from behind","rosto, figura velada, serpente|face, veiled figure, serpent","castelo, joias, coroa de louros|castle, jewels, laurel wreath","dragão|dragon","nuvens|clouds"],
    up:["opções demais|too many options","fantasia|fantasy","projeção|projection","escolha adiada|deferred choice"],
    rev:["clareza emergindo|clarity emerging","opção escolhida|option chosen","ilusão desfeita|illusion dispelled"],
    fn:"A Água sem contorno: o desejo que se multiplica em imagens sem se decidir.|Water without contour: desire multiplying into images without deciding.",
    al:"Só uma taça contém algo real. A carta não diz qual.|Only one cup holds something real. The card does not say which." },
  { id:"c8", n:8, arc:"c", portal:true, name:"Oito de Copas|Eight of Cups", as:"Saturno em Peixes|Saturn in Pisces",
    col:["azul|blue","vermelho|red","cinza|grey"],
    sym:["figura de costas com cajado|figure from behind with a staff","oito taças com um vão|eight cups with a gap","lua em eclipse|eclipsing moon","montanhas e água|mountains and water"],
    up:["partida|departure","abandono consciente|conscious abandonment","busca de sentido|search for meaning","virar as costas|turning away"],
    rev:["retorno|return","partida adiada|postponed departure","hesitação em sair|hesitation to leave"],
    fn:"CARTA-PORTAL: a saída deliberada do que funcionava mas deixou de bastar.|PORTAL CARD: the deliberate exit from what worked but stopped being enough.",
    al:"As taças não estão quebradas. Ele deixa algo intacto para trás.|The cups are not broken. He leaves something intact behind." },
  { id:"c9", n:9, arc:"c", name:"Nove de Copas|Nine of Cups", as:"Júpiter em Peixes|Jupiter in Pisces",
    col:["azul|blue","amarelo|yellow","vermelho|red"],
    sym:["nove taças em arco|nine cups in an arc","mesa coberta|draped table","braços cruzados|crossed arms","chapéu vermelho|red hat"],
    up:["satisfação|satisfaction","desejo atendido|wish granted","prazer|pleasure","conforto|comfort"],
    rev:["satisfação superficial|shallow satisfaction","desejo cumprido sem sentido|wish fulfilled without meaning","excesso|excess"],
    fn:"O contentamento pessoal da Água — completo em si e ainda solitário.|Water's personal contentment — complete in itself and still solitary.",
    al:"Ele está sozinho diante de nove taças. É a única cadeira à mesa.|He sits alone before nine cups. It is the only chair at the table." },
  { id:"c10", n:10, arc:"c", name:"Dez de Copas|Ten of Cups", as:"Marte em Peixes|Mars in Pisces",
    col:["azul|blue","verde|green","amarelo|yellow"],
    sym:["arco-íris de taças|rainbow of cups","casal de braços abertos|couple with open arms","duas crianças dançando|two dancing children","casa e rio|house and river"],
    up:["plenitude afetiva|emotional fullness","harmonia familiar|family harmony","paz duradoura|lasting peace","pertencimento|belonging"],
    rev:["harmonia aparente|apparent harmony","ideal distante|distant ideal","desconexão dentro do vínculo|disconnection within the bond"],
    fn:"O ápice social da Água: o sentimento que se tornou estrutura de vida.|Water's social peak: feeling that has become a life structure.",
    al:"O arco-íris está no céu, não no chão. É promessa, não posse.|The rainbow is in the sky, not on the ground. It is promise, not possession." },
  { id:"cP", n:11, arc:"c", name:"Valete de Copas|Page of Cups", as:"Terra da Água|Earth of Water",
    col:["azul|blue","rosa|pink","amarelo|yellow"],
    sym:["peixe saindo da taça|fish emerging from the cup","túnica com flores de lótus|tunic with lotus flowers","mar ondulado atrás|wavy sea behind","boina azul|blue beret"],
    up:["mensagem afetiva|emotional message","sensibilidade|sensitivity","imaginação|imagination","proposta sincera|sincere offer"],
    rev:["sensibilidade ferida|wounded sensitivity","mensagem não enviada|message unsent","imaturidade emocional|emotional immaturity"],
    fn:"A Terra dentro da Água: o sentimento novo que procura forma concreta.|Earth within Water: new feeling looking for concrete form.",
    al:"O peixe fala e ele não parece surpreso. O inconsciente já está falando com você.|The fish speaks and he seems unsurprised. The unconscious is already speaking to you." },
  { id:"cN", n:12, arc:"c", name:"Cavaleiro de Copas|Knight of Cups", as:"Ar da Água|Air of Water",
    col:["cinza|grey","azul|blue","vermelho|red"],
    sym:["elmo e botas com asas|winged helmet and boots","cavalo em passo lento|slow-stepping horse","rio à frente|river ahead","peixe na sobreveste|fish on the surcoat"],
    up:["proposta romântica|romantic proposal","idealismo|idealism","convite|invitation","charme|charm"],
    rev:["promessa vazia|empty promise","idealismo desiludido|disillusioned idealism","avanço lento demais|advance too slow"],
    fn:"O Ar dentro da Água: o sentimento que virou mensagem e se põe em movimento.|Air within Water: feeling turned message and set in motion.",
    al:"O cavalo caminha, não galopa. Não espere pressa desta oferta.|The horse walks, it does not gallop. Expect no haste from this offer." },
  { id:"cQ", n:13, arc:"c", name:"Rainha de Copas|Queen of Cups", as:"Água da Água|Water of Water",
    col:["azul|blue","branco|white","cinza|grey"],
    sym:["taça fechada e ornamentada|ornate covered cup","trono com sereias|throne with mermaids","pedras aos pés|stones at her feet","olhar fixo na taça|gaze fixed on the cup"],
    up:["empatia profunda|deep empathy","intuição emocional|emotional intuition","acolhimento|holding space","serenidade|serenity"],
    rev:["absorção do sentimento alheio|absorbing others' feelings","limite emocional frágil|fragile emotional boundary","retraimento|withdrawal"],
    fn:"A Água da Água: a capacidade de sentir sem se dissolver no que se sente.|Water of Water: the ability to feel without dissolving into the feeling.",
    al:"A única taça fechada do baralho. Ela sabe algo que não mostra.|The only closed cup in the deck. She knows something she does not show." },
  { id:"cK", n:14, arc:"c", name:"Rei de Copas|King of Cups", as:"Fogo da Água|Fire of Water",
    col:["azul|blue","amarelo|yellow","vermelho|red"],
    sym:["trono sobre mar agitado|throne on a turbulent sea","navio ao fundo|ship in the background","peixe saltando|leaping fish","amuleto de peixe|fish amulet","pés sem tocar a água|feet not touching the water"],
    up:["maturidade emocional|emotional maturity","conselho compassivo|compassionate counsel","controle sereno|serene control","diplomacia|diplomacy"],
    rev:["emoção reprimida|repressed emotion","frieza calculada|calculated coldness","manipulação afetiva|emotional manipulation"],
    fn:"O Fogo da Água: a vontade aplicada ao sentimento — governar sem endurecer.|Fire of Water: will applied to feeling — to govern without hardening.",
    al:"O trono flutua num mar agitado. A calma dele é trabalho constante, não natureza.|The throne floats on a rough sea. His calm is constant work, not nature." },
];

const SWORDS = [
  { id:"s1", n:1, arc:"s", name:"Ás de Espadas|Ace of Swords", as:"Raiz do Ar|Root of Air",
    col:["cinza|grey","branco|white","amarelo|yellow"],
    sym:["mão saindo da nuvem|hand from a cloud","coroa com oliveira e palma|crown with olive and palm","montanhas recortadas|jagged mountains","seis yods|six yods"],
    up:["clareza cortante|cutting clarity","verdade|truth","decisão|decision","ideia definidora|defining idea"],
    rev:["clareza confusa|clouded clarity","verdade usada como arma|truth used as a weapon","decisão travada|stalled decision"],
    fn:"A semente pura do Ar: o pensamento que separa uma coisa da outra.|The pure seed of Air: the thought that separates one thing from another.",
    al:"A lâmina corta nos dois sentidos. Clareza também machuca.|The blade cuts both ways. Clarity wounds too." },
  { id:"s2", n:2, arc:"s", name:"Dois de Espadas|Two of Swords", as:"Lua em Libra|Moon in Libra",
    col:["cinza|grey","branco|white","azul|blue"],
    sym:["venda nos olhos|blindfold","espadas cruzadas no peito|swords crossed at the chest","mar com rochas|sea with rocks","lua crescente|crescent moon","banco de pedra|stone bench"],
    up:["impasse|impasse","decisão evitada|avoided decision","trégua tensa|tense truce","informação bloqueada|blocked information"],
    rev:["venda caindo|blindfold slipping","impasse rompido|impasse broken","verdade admitida|truth admitted"],
    fn:"O Ar em equilíbrio forçado: pensar duas coisas ao mesmo tempo é não decidir.|Air in forced balance: holding two things at once is choosing neither.",
    al:"A venda foi colocada por ela mesma. O mar atrás continua se movendo.|The blindfold is self-applied. The sea behind keeps moving." },
  { id:"s3", n:3, arc:"s", name:"Três de Espadas|Three of Swords", as:"Saturno em Libra|Saturn in Libra",
    col:["cinza|grey","vermelho|red","azul|blue"],
    sym:["coração atravessado|pierced heart","três espadas|three swords","chuva|rain","nuvens carregadas|heavy clouds","ausência de figura humana|no human figure"],
    up:["dor nomeada|named pain","separação|separation","verdade que fere|wounding truth","luto agudo|acute grief"],
    rev:["dor sendo processada|pain being processed","cicatrização|healing over","recusa em sentir|refusal to feel"],
    fn:"O ponto em que o intelecto atravessa o afeto — e o afeto sente.|The point where intellect pierces feeling — and feeling registers it.",
    al:"Não há ninguém na carta. Esta dor não tem culpado a apontar.|There is no one in the card. This pain has no one to blame." },
  { id:"s4", n:4, arc:"s", name:"Quatro de Espadas|Four of Swords", as:"Júpiter em Libra|Jupiter in Libra",
    col:["cinza|grey","amarelo|yellow","vermelho|red"],
    sym:["efígie sobre o túmulo|effigy on a tomb","três espadas na parede|three swords on the wall","uma espada sob o corpo|one sword beneath the body","vitral|stained glass window","mãos em prece|hands in prayer"],
    up:["repouso|rest","convalescença|convalescence","retiro necessário|necessary retreat","suspensão|suspension"],
    rev:["retomada|resuming","repouso interrompido|interrupted rest","recusa em parar|refusal to stop"],
    fn:"O Ar em silêncio: a mente que precisa parar para não se despedaçar.|Air in silence: the mind that must stop to avoid shattering.",
    al:"A figura não está morta — está deitada. Repouso não é desistência.|The figure is not dead — it is lying down. Rest is not surrender." },
  { id:"s5", n:5, arc:"s", name:"Cinco de Espadas|Five of Swords", as:"Vênus em Aquário|Venus in Aquarius",
    col:["cinza|grey","verde|green","vermelho|red"],
    sym:["figura recolhendo espadas|figure gathering swords","sorriso de canto|smirk","duas figuras se afastando|two figures walking away","nuvens irregulares|ragged clouds","mar agitado|choppy sea"],
    up:["vitória vazia|hollow victory","conflito com custo|costly conflict","humilhação|humiliation","autointeresse|self-interest"],
    rev:["reconciliação|reconciliation","recuo do embate|withdrawal from the fight","custo reconhecido|cost acknowledged"],
    fn:"O Ar usado para vencer em vez de compreender.|Air used to win rather than to understand.",
    al:"Ele ganhou e ficou sozinho. Pergunte se este é o preço que você aceita.|He won and stands alone. Ask whether this is the price you accept." },
  { id:"s6", n:6, arc:"s", portal:true, name:"Seis de Espadas|Six of Swords", as:"Mercúrio em Aquário|Mercury in Aquarius",
    col:["cinza|grey","azul|blue","verde|green"],
    sym:["barqueiro com vara|ferryman with a pole","mulher encapuzada e criança|hooded woman and child","seis espadas fincadas no barco|six swords planted in the boat","água agitada de um lado, calma do outro|rough water on one side, calm on the other"],
    up:["travessia|passage","transição|transition","afastamento necessário|necessary distancing","cura em movimento|healing in motion"],
    rev:["travessia adiada|postponed crossing","bagagem que não se larga|baggage not put down","retorno ao que se deixou|return to what was left"],
    fn:"CARTA-PORTAL: a passagem literal de um estado a outro. Abre experiência arquetípica de transição.|PORTAL CARD: the literal passage from one state to another. Opens the archetypal experience of transition.",
    al:"As espadas viajam junto. Você leva a dor para o outro lado.|The swords travel along. You carry the pain to the other side." },
  { id:"s7", n:7, arc:"s", name:"Sete de Espadas|Seven of Swords", as:"Lua em Aquário|Moon in Aquarius",
    col:["amarelo|yellow","laranja|orange","vermelho|red"],
    sym:["figura na ponta dos pés|figure on tiptoe","cinco espadas nos braços|five swords in his arms","duas espadas deixadas|two swords left behind","acampamento ao fundo|camp in the background","olhar para trás|backward glance"],
    up:["estratégia solitária|solitary strategy","furtividade|stealth","meia-verdade|half-truth","atalho|shortcut"],
    rev:["estratégia exposta|strategy exposed","confissão|confession","devolução|returning what was taken"],
    fn:"O Ar operando por desvio: a inteligência que evita o confronto direto.|Air operating by detour: intelligence avoiding direct confrontation.",
    al:"Ele deixou duas espadas para trás. O plano já está incompleto.|He left two swords behind. The plan is already incomplete." },
  { id:"s8", n:8, arc:"s", name:"Oito de Espadas|Eight of Swords", as:"Júpiter em Gêmeos|Jupiter in Gemini",
    col:["cinza|grey","vermelho|red","amarelo|yellow"],
    sym:["figura amarrada e vendada|bound, blindfolded figure","oito espadas em semicírculo|eight swords in a half-circle","castelo na colina|castle on the hill","lama sob os pés|mud underfoot","pés livres|free feet"],
    up:["aprisionamento mental|mental imprisonment","vitimização|victimhood","restrição percebida|perceived restriction","paralisia|paralysis"],
    rev:["laços afrouxando|bonds loosening","saída percebida|exit noticed","autorresponsabilidade|self-responsibility"],
    fn:"A prisão construída pelo próprio pensamento — a mais difícil de ver.|The prison built by thought itself — the hardest kind to see.",
    al:"As espadas não formam círculo fechado. Há saída atrás dela.|The swords do not form a closed circle. There is a way out behind her." },
  { id:"s9", n:9, arc:"s", name:"Nove de Espadas|Nine of Swords", as:"Marte em Gêmeos|Mars in Gemini",
    col:["preto|black","branco|white","vermelho|red"],
    sym:["figura sentada na cama|figure sitting up in bed","rosto nas mãos|face in hands","nove espadas na parede|nine swords on the wall","colcha com rosas e signos|quilt with roses and zodiac signs","entalhe de duelo na cama|duel carving on the bed"],
    up:["angústia|anguish","insônia|insomnia","culpa|guilt","medo noturno|night fear","ruminação|rumination"],
    rev:["o medo dito em voz alta|fear spoken aloud","alívio ao amanhecer|relief at dawn","pesadelo se dissipando|nightmare dissipating"],
    fn:"O Ar voltado contra si mesmo na ausência de luz e de testemunha.|Air turned against itself in the absence of light and witness.",
    al:"As espadas estão na parede, não no corpo. O sofrimento é real e a ferida não.|The swords are on the wall, not in the body. The suffering is real and the wound is not." },
  { id:"s10", n:10, arc:"s", name:"Dez de Espadas|Ten of Swords", as:"Sol em Gêmeos|Sun in Gemini",
    col:["preto|black","amarelo|yellow","vermelho|red"],
    sym:["figura caída com dez espadas|fallen figure with ten swords","céu negro|black sky","água imóvel|still water","alvorada no horizonte|dawn on the horizon","mão em bênção|hand in benediction"],
    up:["fim absoluto|absolute ending","fundo do poço|rock bottom","traição|betrayal","colapso do ciclo mental|collapse of the mental cycle"],
    rev:["recuperação lenta|slow recovery","o pior já passou|the worst has passed","resistência ao fim|resistance to the ending"],
    fn:"O Ar levado ao extremo: o pensamento que se esgota completamente.|Air at its extreme: thought exhausting itself entirely.",
    al:"O céu está negro e o horizonte, dourado. Ambas as coisas são verdadeiras.|The sky is black and the horizon golden. Both are true." },
  { id:"sP", n:11, arc:"s", name:"Valete de Espadas|Page of Swords", as:"Terra do Ar|Earth of Air",
    col:["verde|green","cinza|grey","vermelho|red"],
    sym:["espada erguida com as duas mãos|sword raised in both hands","céu ventoso|windy sky","dez pássaros|ten birds","terreno acidentado|uneven ground","olhar para trás|looking backward"],
    up:["curiosidade aguda|sharp curiosity","vigilância|watchfulness","notícia|news","aprendizado mental|mental learning"],
    rev:["mexerico|gossip","curiosidade invasiva|invasive curiosity","informação mal usada|misused information"],
    fn:"A Terra dentro do Ar: a ideia jovem que quer testar seu próprio gume.|Earth within Air: the young idea wanting to test its own edge.",
    al:"Ele olha para trás enquanto avança. A vigilância aqui é medo disfarçado.|He looks back while moving forward. The watchfulness here is fear in disguise." },
  { id:"sN", n:12, arc:"s", name:"Cavaleiro de Espadas|Knight of Swords", as:"Ar do Ar|Air of Air",
    col:["cinza|grey","vermelho|red","branco|white"],
    sym:["cavalo em galope|galloping horse","espada apontada à frente|sword pointed forward","árvores curvadas pelo vento|wind-bent trees","pássaros dispersos|scattered birds","capa esvoaçante|streaming cloak"],
    up:["investida|charge","argumento direto|direct argument","velocidade mental|mental speed","determinação|determination"],
    rev:["agressividade verbal|verbal aggression","pressa sem estratégia|haste without strategy","investida que se esgota|charge that burns out"],
    fn:"O Ar do Ar: o intelecto em estado puro de ataque, sem freio corporal.|Air of Air: intellect in pure attacking state, with no bodily brake.",
    al:"Ele não olha para onde vai. Só para onde a espada aponta.|He does not look where he is going. Only where the sword points." },
  { id:"sQ", n:13, arc:"s", name:"Rainha de Espadas|Queen of Swords", as:"Água do Ar|Water of Air",
    col:["cinza|grey","azul|blue","branco|white"],
    sym:["espada erguida na vertical|sword held upright","mão esquerda estendida|left hand extended","borboletas e querubim no trono|butterflies and cherub on the throne","nuvens abaixo dela|clouds below her","perfil severo|severe profile"],
    up:["lucidez|lucidity","limite claro|clear boundary","honestidade|honesty","experiência destilada|distilled experience"],
    rev:["frieza|coldness","crítica excessiva|excessive criticism","isolamento pela lucidez|isolation through clarity"],
    fn:"A Água dentro do Ar: a inteligência informada pela perda — clara sem ser cruel.|Water within Air: intelligence informed by loss — clear without cruelty.",
    al:"A mão estendida convida. A espada permanece erguida. Ambas ao mesmo tempo.|The extended hand invites. The sword stays raised. Both at once." },
  { id:"sK", n:14, arc:"s", name:"Rei de Espadas|King of Swords", as:"Fogo do Ar|Fire of Air",
    col:["azul|blue","roxo|purple","cinza|grey"],
    sym:["borboletas e silfos no trono|butterflies and sylphs on the throne","espada levemente inclinada|slightly tilted sword","dois pássaros|two birds","olhar frontal|frontal gaze","nuvens estáticas|static clouds"],
    up:["julgamento imparcial|impartial judgement","autoridade intelectual|intellectual authority","ética|ethics","conselho estruturado|structured counsel"],
    rev:["racionalização|rationalisation","autoridade fria|cold authority","poder do argumento sobre o vínculo|argument prevailing over bond"],
    fn:"O Fogo do Ar: a vontade aplicada ao pensamento — decidir e sustentar a decisão.|Fire of Air: will applied to thought — to decide and stand by the decision.",
    al:"A espada pende levemente. Nem mesmo ele está totalmente imparcial.|The sword tilts slightly. Not even he is entirely impartial." },
];

const PENTS = [
  { id:"p1", n:1, arc:"p", name:"Ás de Ouros|Ace of Pentacles", as:"Raiz da Terra|Root of Earth",
    col:["verde|green","branco|white","dourado|gold"],
    sym:["mão saindo da nuvem|hand from a cloud","jardim com lírios|garden with lilies","arco de sebe|hedge archway","montanha ao longe|distant mountain","caminho|path"],
    up:["oportunidade material|material opportunity","novo recurso|new resource","semente concreta|concrete seed","saúde|health"],
    rev:["oportunidade não aproveitada|opportunity untaken","recurso mal aplicado|misapplied resource","ganho adiado|delayed gain"],
    fn:"A semente pura da Terra: a possibilidade que ainda exige plantio.|The pure seed of Earth: possibility that still requires planting.",
    al:"O arco leva às montanhas. A oferta é um começo de caminho, não o destino.|The arch leads to the mountains. The offer is the start of a road, not the destination." },
  { id:"p2", n:2, arc:"p", name:"Dois de Ouros|Two of Pentacles", as:"Júpiter em Capricórnio|Jupiter in Capricorn",
    col:["laranja|orange","verde|green","azul|blue"],
    sym:["lemniscata verde|green lemniscate","dois ouros em malabarismo|two juggled pentacles","navios em ondas altas|ships on high waves","chapéu alto|tall hat","postura em dança|dancing stance"],
    up:["equilíbrio dinâmico|dynamic balance","adaptação|adaptation","prioridades em jogo|competing priorities","flexibilidade|flexibility"],
    rev:["sobrecarga|overload","desequilíbrio|imbalance","uma bola caindo|one ball dropping"],
    fn:"A Terra em movimento: manter dois pesos exige dança, não força.|Earth in motion: holding two weights takes dance, not force.",
    al:"Os navios atrás enfrentam ondas altas. O equilíbrio é sobre mar revolto.|The ships behind face high waves. The balance is over rough sea." },
  { id:"p3", n:3, arc:"p", name:"Três de Ouros|Three of Pentacles", as:"Marte em Capricórnio|Mars in Capricorn",
    col:["cinza|grey","preto|black","amarelo|yellow"],
    sym:["escultor no banco|sculptor on a bench","monge e arquiteto com planta|monk and architect with plans","arco de catedral|cathedral arch","três ouros no arco|three pentacles in the arch"],
    up:["colaboração|collaboration","competência reconhecida|recognised competence","obra em construção|work under construction","aprendizado aplicado|applied learning"],
    rev:["colaboração truncada|broken collaboration","competência ignorada|competence overlooked","trabalho em desalinhamento|misaligned work"],
    fn:"A Terra socializada: o ofício individual encontrando a estrutura coletiva.|Socialised Earth: individual craft meeting collective structure.",
    al:"O artesão está de pé sobre o banco, acima dos que trazem o plano.|The craftsman stands on the bench, above those holding the plan." },
  { id:"p4", n:4, arc:"p", name:"Quatro de Ouros|Four of Pentacles", as:"Sol em Capricórnio|Sun in Capricorn",
    col:["preto|black","vermelho|red","cinza|grey"],
    sym:["ouro abraçado ao peito|pentacle clutched to the chest","um ouro sobre a coroa|one pentacle on the crown","dois sob os pés|two under the feet","cidade ao fundo|city behind","banco isolado|isolated bench"],
    up:["retenção|holding on","segurança material|material security","controle|control","poupança|saving"],
    rev:["afrouxamento|loosening","generosidade|generosity","medo de perder exposto|fear of loss exposed"],
    fn:"A Terra imobilizada: a estabilidade que virou rigidez.|Immobilised Earth: stability turned rigid.",
    al:"Com quatro ouros ocupados, ele não tem uma mão livre.|With four pentacles occupied, he has no free hand." },
  { id:"p5", n:5, arc:"p", name:"Cinco de Ouros|Five of Pentacles", as:"Mercúrio em Touro|Mercury in Taurus",
    col:["branco|white","cinza|grey","amarelo|yellow"],
    sym:["dois mendigos na neve|two beggars in the snow","vitral iluminado|lit stained glass window","muletas|crutches","bandagem|bandage","sino no pescoço|bell at the neck"],
    up:["privação|deprivation","exclusão|exclusion","dificuldade material|material hardship","fé abalada|shaken faith"],
    rev:["recuperação|recovery","ajuda aceita|help accepted","fim do inverno|end of winter"],
    fn:"A Terra em falta: a experiência de estar do lado de fora.|Earth in scarcity: the experience of being outside.",
    al:"O vitral está aceso e eles passam direto. O abrigo existe e não é procurado.|The window is lit and they walk past. Shelter exists and is not sought." },
  { id:"p6", n:6, arc:"p", portal:true, name:"Seis de Ouros|Six of Pentacles", as:"Lua em Touro|Moon in Taurus",
    col:["vermelho|red","cinza|grey","amarelo|yellow"],
    sym:["balança na mão esquerda|scales in the left hand","moedas caindo|falling coins","dois mendigos ajoelhados|two kneeling beggars","túnica vermelha|red robe"],
    up:["generosidade|generosity","troca desigual|unequal exchange","recebimento|receiving","equilíbrio de dar e receber|balance of giving and receiving"],
    rev:["doação com condição|giving with strings","dívida|debt","poder disfarçado de caridade|power disguised as charity"],
    fn:"CARTA-PORTAL: expõe a arquitetura do poder dentro de todo ato de dar.|PORTAL CARD: exposes the architecture of power inside every act of giving.",
    al:"Ele segura a balança. Quem mede decide quanto cabe a cada um.|He holds the scales. Whoever measures decides each person's share." },
  { id:"p7", n:7, arc:"p", name:"Sete de Ouros|Seven of Pentacles", as:"Saturno em Touro|Saturn in Taurus",
    col:["verde|green","laranja|orange","azul|blue"],
    sym:["figura apoiada na enxada|figure leaning on a hoe","sete ouros no arbusto|seven pentacles on the bush","um ouro no chão|one pentacle on the ground","olhar contemplativo|contemplative gaze"],
    up:["avaliação|assessment","paciência|patience","investimento em curso|investment in progress","dúvida sobre o retorno|doubt about the return"],
    rev:["impaciência|impatience","colheita precipitada|premature harvest","esforço reavaliado|effort reassessed"],
    fn:"A Terra no tempo: o intervalo entre o plantio e a colheita, onde nasce a dúvida.|Earth in time: the interval between planting and harvest, where doubt is born.",
    al:"Ele parou de trabalhar para olhar. A pausa é a decisão real desta carta.|He has stopped working to look. The pause is this card's real decision." },
  { id:"p8", n:8, arc:"p", name:"Oito de Ouros|Eight of Pentacles", as:"Sol em Virgem|Sun in Virgo",
    col:["amarelo|yellow","azul|blue","cinza|grey"],
    sym:["artesão no banco|craftsman at the bench","seis ouros pendurados|six pentacles hung up","um na mão, um no chão|one in hand, one on the ground","cidade ao longe|town in the distance","avental|apron"],
    up:["dedicação|dedication","aprimoramento|refinement","repetição produtiva|productive repetition","ofício|craft"],
    rev:["repetição sem sentido|meaningless repetition","perfeccionismo|perfectionism","aprendizado interrompido|interrupted apprenticeship"],
    fn:"A Terra disciplinada: o domínio construído por acúmulo de horas.|Disciplined Earth: mastery built by accumulated hours.",
    al:"A cidade está longe e ele está de costas para ela.|The town is far and his back is to it." },
  { id:"p9", n:9, arc:"p", portal:true, name:"Nove de Ouros|Nine of Pentacles", as:"Vênus em Virgem|Venus in Virgo",
    col:["amarelo|yellow","verde|green","vermelho|red"],
    sym:["falcão encapuzado na mão|hooded falcon on the hand","parreiras carregadas|laden grapevines","caracol no chão|snail on the ground","mansão ao fundo|manor in the background","jardim murado|walled garden"],
    up:["autossuficiência|self-sufficiency","conquista pessoal|personal achievement","refinamento|refinement","desfrute merecido|earned enjoyment"],
    rev:["independência custosa|costly independence","solidão dourada|gilded solitude","dependência disfarçada|disguised dependence"],
    fn:"CARTA-PORTAL: a autonomia material como estado arquetípico — e seu preço.|PORTAL CARD: material autonomy as an archetypal state — and its price.",
    al:"O falcão está encapuzado. Ela domesticou algo selvagem em si para chegar aqui.|The falcon is hooded. She has tamed something wild in herself to arrive here." },
  { id:"p10", n:10, arc:"p", portal:true, name:"Dez de Ouros|Ten of Pentacles", as:"Mercúrio em Virgem|Mercury in Virgo",
    col:["amarelo|yellow","branco|white","vermelho|red"],
    sym:["ancião com dois cães|old man with two dogs","casal e criança|couple and child","arco com brasão|arch with a coat of arms","dez ouros em Árvore da Vida|ten pentacles in a Tree of Life pattern","balança no brasão|scales on the crest"],
    up:["legado|legacy","riqueza estabelecida|established wealth","família|family","permanência|permanence","raízes|roots"],
    rev:["legado em disputa|contested legacy","estrutura familiar tensionada|strained family structure","segurança questionada|questioned security"],
    fn:"CARTA-PORTAL: o padrão dos dez ouros desenha a Árvore da Vida — a matéria revelando o mapa espiritual inteiro.|PORTAL CARD: the ten pentacles trace the Tree of Life — matter revealing the entire spiritual map.",
    al:"O ancião está fora do arco, à margem da cena que ele construiu.|The old man sits outside the arch, at the edge of the scene he built." },
  { id:"pP", n:11, arc:"p", name:"Valete de Ouros|Page of Pentacles", as:"Terra da Terra|Earth of Earth",
    col:["verde|green","marrom|brown","amarelo|yellow"],
    sym:["ouro erguido e contemplado|pentacle raised and contemplated","campo arado|ploughed field","bosque ao fundo|grove in the background","postura absorta|absorbed stance"],
    up:["estudo|study","novo ofício|new craft","proposta prática|practical offer","foco paciente|patient focus"],
    rev:["procrastinação|procrastination","estudo sem aplicação|study without application","proposta que não se concretiza|offer that does not materialise"],
    fn:"A Terra da Terra: o começo mais concreto possível — aprender fazendo.|Earth of Earth: the most concrete beginning possible — learning by doing.",
    al:"O campo já está arado e ele não está trabalhando nele.|The field is already ploughed and he is not working it." },
  { id:"pN", n:12, arc:"p", name:"Cavaleiro de Ouros|Knight of Pentacles", as:"Ar da Terra|Air of Earth",
    col:["preto|black","verde|green","vermelho|red"],
    sym:["cavalo negro parado|stationary black horse","ouro estendido na palma|pentacle held out on the palm","campo arado|ploughed field","armadura completa|full armour","ramo verde no elmo|green sprig on the helm"],
    up:["método|method","confiabilidade|reliability","progresso lento e certo|slow, sure progress","compromisso cumprido|commitment kept"],
    rev:["estagnação|stagnation","excesso de cautela|excessive caution","rotina que virou inércia|routine turned inertia"],
    fn:"O Ar dentro da Terra: o único cavaleiro parado — o movimento é intenção, não velocidade.|Air within Earth: the only stationary knight — movement here is intention, not speed.",
    al:"O cavalo está imóvel. Confiabilidade e inércia usam a mesma armadura.|The horse is still. Reliability and inertia wear the same armour." },
  { id:"pQ", n:13, arc:"p", name:"Rainha de Ouros|Queen of Pentacles", as:"Água da Terra|Water of Earth",
    col:["verde|green","vermelho|red","amarelo|yellow"],
    sym:["coelho no canto inferior|rabbit in the lower corner","caramanchão florido|flowering arbour","cabras e frutas no trono|goats and fruit on the throne","olhar sobre o ouro no colo|gaze on the pentacle in her lap"],
    up:["cuidado prático|practical care","nutrição|nourishment","abundância gerida|managed abundance","presença corporal|bodily presence"],
    rev:["cuidado que se esquece de si|care that forgets itself","dependência material|material dependence","abundância retida|withheld abundance"],
    fn:"A Água dentro da Terra: o afeto que se expressa como provisão concreta.|Water within Earth: affection expressed as concrete provision.",
    al:"O coelho é fertilidade e também fuga. Ela pode estar se escondendo no cuidado.|The rabbit is fertility and also flight. She may be hiding inside the caretaking." },
  { id:"pK", n:14, arc:"p", name:"Rei de Ouros|King of Pentacles", as:"Fogo da Terra|Fire of Earth",
    col:["preto|black","verde|green","dourado|gold"],
    sym:["manto de parreiras|grapevine robe","cabeças de touro no trono|bull heads on the throne","castelo atrás|castle behind","armadura sob o manto|armour beneath the robe","pé sobre cabeça de javali|foot on a boar's head"],
    up:["prosperidade consolidada|consolidated prosperity","provisão|provision","domínio material|material mastery","generosidade estável|steady generosity"],
    rev:["apego ao patrimônio|attachment to holdings","controle pelo dinheiro|control through money","estagnação confortável|comfortable stagnation"],
    fn:"O Fogo da Terra: a vontade que constrói e mantém o mundo material.|Fire of Earth: the will that builds and maintains the material world.",
    al:"Há armadura sob o manto de uvas. Ele ainda se prepara para uma guerra que já venceu.|There is armour under the grape robe. He still readies for a war he already won." },
];

const CARDS = [...MAJORS, ...WANDS, ...CUPS, ...SWORDS, ...PENTS].map((c) => ({
  ...c,
  el: c.arc === "M" ? c.el : { w:"Fogo|Fire", c:"Água|Water", s:"Ar|Air", p:"Terra|Earth" }[c.arc],
  suit: c.arc === "M" ? "Arcanos Maiores|Major Arcana"
      : { w:"Paus|Wands", c:"Copas|Cups", s:"Espadas|Swords", p:"Ouros|Pentacles" }[c.arc],
}));


const EL_KEY = (c) => L(c.el, "en"); // Fire | Water | Air | Earth

const norm = (s) => String(s || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9 ]/g, "").trim();
const CARDS_BY_LEN = [...CARDS].sort((a, b) => L(b.name, "pt").length - L(a.name, "pt").length);
const matchCard = (raw) => {
  const q = norm(raw);
  if (!q) return null;
  // 1) nome exato (uso programático, ex.: comparar strings vindas de uma lista fechada)
  let hit = CARDS.find((c) => norm(L(c.name, "en")) === q || norm(L(c.name, "pt")) === q);
  if (hit) return hit;
  // 2) nome da carta mencionado dentro de um texto livre — nomes mais longos primeiro,
  //    para "Cavaleiro de Copas" não ser ofuscado por um casamento parcial menor
  hit = CARDS_BY_LEN.find((c) => q.includes(norm(L(c.name, "pt"))) || q.includes(norm(L(c.name, "en"))));
  return hit || null;
};

export { L, LA, CARDS, EL_KEY, norm, matchCard };
