import { L, LA, CARDS } from "./data.jsx";

const SPREADS = [
  {
    id:"one", cols:1, rows:1,
    name:"Carta Única|Single Card",
    use:"Foco diário, pergunta fechada, ou clarificação de outra carta.|Daily focus, a closed question, or clarifying another card.",
    why:"Sem posição, a carta responde com sua totalidade. É a tiragem mais difícil de ler bem justamente porque nada restringe o campo — o significado precisa vir inteiro da carta e da pergunta.|With no position, the card answers with its totality. It is the hardest spread to read well precisely because nothing narrows the field — meaning must come entirely from the card and the question.",
    pos:[{c:1,r:1,label:"A Carta|The Card",q:"O que preciso ver agora?|What do I need to see right now?",why:"Posição neutra: não modifica a carta, apenas a expõe.|A neutral position: it does not modify the card, only exposes it."}]
  },
  {
    id:"three", cols:3, rows:1,
    name:"Três Cartas|Three Cards",
    use:"Movimento, causalidade, ou decomposição de uma situação em três forças.|Movement, causality, or breaking a situation into three forces.",
    why:"Três é o número mínimo para haver narrativa: começo, meio e fim; ou tese, antítese e síntese. A leitura da esquerda para a direita cria um vetor de tempo, e a carta do meio recebe dignidade elemental dos dois lados — é a única com dois vizinhos.|Three is the minimum for narrative: beginning, middle, end; or thesis, antithesis, synthesis. Reading left to right creates a time vector, and the middle card receives elemental dignity from both sides — the only one with two neighbours.",
    variants:[
      {n:"Passado · Presente · Futuro|Past · Present · Future", d:"Vetor temporal. Use quando a pergunta é sobre trajetória.|Temporal vector. Use when the question is about trajectory."},
      {n:"Situação · Ação · Resultado|Situation · Action · Outcome", d:"Vetor causal. Use quando a pergunta é sobre o que fazer.|Causal vector. Use when the question is about what to do."},
      {n:"O que ajuda · O que atrapalha · O que não vejo|Helps · Hinders · Unseen", d:"Vetor diagnóstico. Use quando a pergunta é sobre um bloqueio.|Diagnostic vector. Use when the question is about a blockage."},
      {n:"Corpo · Mente · Espírito|Body · Mind · Spirit", d:"Vetor vertical. Use para leituras de estado interno.|Vertical vector. Use for readings of inner state."}
    ],
    pos:[
      {c:1,r:1,label:"Primeira|First",q:"O que está atrás ou abaixo disso?|What lies behind or beneath this?",why:"A origem. Recebe dignidade só da direita — sua influência é unidirecional.|The origin. It receives dignity only from the right — its influence is one-directional."},
      {c:2,r:1,label:"Segunda|Second",q:"Onde está o núcleo?|Where is the core?",why:"O eixo. Única carta modificada pelos dois lados; se as vizinhas forem elementos contrários entre si, elas se anulam e esta carta lê-se sozinha (regra de Mathers).|The axis. The only card modified from both sides; if the flanking cards are contrary to each other they cancel out and this card reads alone (Mathers' rule)."},
      {c:3,r:1,label:"Terceira|Third",q:"Para onde isso tende?|Where does this tend?",why:"O destino provável. Recebe dignidade só da esquerda.|The likely outcome. It receives dignity only from the left."}
    ]
  },
  {
    id:"celtic", cols:4, rows:4,
    name:"Cruz Celta|Celtic Cross",
    use:"Situação complexa, com muitas forças em jogo e um horizonte a médio prazo.|A complex situation with many forces at play and a mid-range horizon.",
    why:"Publicada por A. E. Waite em 'The Pictorial Key to the Tarot' (1910), sob o nome 'An Ancient Celtic Method of Divination' — nome de marketing, não linhagem histórica: o método vem do meio da Golden Dawn vitoriana, não da Irlanda pré-cristã. Reconhecer isso importa: a Cruz Celta é um sistema desenhado, e portanto discutível. As posições 3/4 e 5/6 variam entre escolas. A geometria tem duas metades: a Cruz (1–6) é o que está acontecendo, o Bastão (7–10) é o que age sobre isso a partir de fora e para onde vai.|Published by A. E. Waite in 'The Pictorial Key to the Tarot' (1910) as 'An Ancient Celtic Method of Divination' — a marketing name, not a historical lineage: the method comes from the Victorian Golden Dawn milieu, not pre-Christian Ireland. Recognising this matters: the Celtic Cross is a designed system, and therefore arguable. Positions 3/4 and 5/6 vary between schools. The geometry has two halves: the Cross (1–6) is what is happening, the Staff (7–10) is what acts on it from outside and where it is going.",
    pos:[
      {c:2,r:2,label:"Centro|Heart of the Matter",q:"Qual é a situação em si?|What is the situation itself?",why:"Ocupa o cruzamento dos eixos porque tudo mais é medido em relação a ela.|It occupies the crossing of the axes because everything else is measured against it."},
      {c:2,r:2,rot:true,label:"Cruzamento|The Crossing",q:"O que atravessa isso — obstáculo ou apoio?|What crosses this — obstacle or support?",why:"Deitada sobre a primeira: a única posição do baralho que não se lê como boa ou má, só como força transversal. Uma carta favorável aqui ainda atravessa.|Laid across the first: the only position that reads as neither good nor bad, only as a transverse force. A favourable card here still cuts across."},
      {c:2,r:3,label:"Base|The Foundation",q:"Qual é a raiz inconsciente disso?|What is the unconscious root of this?",why:"Abaixo, porque sustenta a situação sem ser vista. É o solo.|Below, because it holds the situation up without being seen. It is the ground."},
      {c:1,r:2,label:"Passado Recente|Recent Past",q:"O que acabou de sair de cena?|What has just left the scene?",why:"À esquerda, seguindo a direção da leitura: o que já passou pelo centro.|To the left, following reading direction: what has already passed through the centre."},
      {c:2,r:1,label:"Possível Resultado|Possible Outcome",q:"O que está consciente, no alto da mente?|What is conscious, at the top of the mind?",why:"Acima: o objetivo declarado, a meta que se enxerga. Waite deixou esta posição ambígua e há escolas que a trocam com a 3.|Above: the stated goal, the aim in view. Waite left this position ambiguous and some schools swap it with position 3."},
      {c:3,r:2,label:"Futuro Próximo|Near Future",q:"O que entra em cena a seguir?|What enters the scene next?",why:"À direita: o que vai atravessar o centro em seguida. Prazo curto, não conclusão.|To the right: what will cross the centre next. Short term, not conclusion."},
      {c:4,r:4,label:"Eu|The Self",q:"Como estou me posicionando nisso?|How am I positioning myself in this?",why:"Base do Bastão: tudo que sobe a partir daqui parte da sua própria postura.|Base of the Staff: everything rising from here starts with your own stance."},
      {c:4,r:3,label:"Ambiente|Environment",q:"O que as pessoas e as circunstâncias em volta estão fazendo?|What are the people and circumstances around doing?",why:"Logo acima do Eu, porque o ambiente responde à sua postura antes de responder a qualquer outra coisa.|Just above the Self, because the environment responds to your stance before it responds to anything else."},
      {c:4,r:2,label:"Esperanças & Medos|Hopes & Fears",q:"O que desejo e temo — muitas vezes a mesma coisa?|What do I hope for and fear — often the same thing?",why:"A posição mais subestimada da tiragem. Waite juntou esperança e medo num só lugar deliberadamente: no mesmo assunto, elas costumam ser a mesma imagem vista de dois ângulos.|The most underrated position in the spread. Waite deliberately put hope and fear in one place: on the same subject they are usually the same image seen from two angles.",key:true},
      {c:4,r:1,label:"Resultado|Outcome",q:"Para onde tudo isso converge?|Where does all of this converge?",why:"Topo: resultado provável se nada mudar, não sentença. Lê-se sempre contra a posição 9.|Top: the likely result if nothing changes, not a verdict. Always read it against position 9."}
    ]
  },
  {
    id:"horseshoe", cols:7, rows:1,
    name:"Ferradura|Horseshoe",
    use:"Panorama de uma questão prática, entre a leveza de três cartas e o peso da Cruz Celta.|An overview of a practical question, between the lightness of three cards and the weight of the Celtic Cross.",
    why:"Sete cartas em arco. Cada carta tem exatamente dois vizinhos (salvo as pontas), o que faz desta a melhor tiragem para praticar dignidades elementais em cadeia: o arco inteiro pode ser lido como uma sequência de tríades sobrepostas.|Seven cards in an arc. Each card has exactly two neighbours (except the ends), making this the best spread for practising elemental dignities in a chain: the whole arc can be read as a series of overlapping triads.",
    pos:[
      {c:1,r:1,label:"Passado|Past",q:"De onde isso vem?|Where does this come from?",why:"Ponta esquerda: só influencia, não é influenciada.|Left end: it influences only, it is not influenced."},
      {c:2,r:1,label:"Presente|Present",q:"Onde está agora?|Where is it now?",why:"Primeira carta com dois vizinhos — já entra em dignidade.|The first card with two neighbours — dignity begins here."},
      {c:3,r:1,label:"Influências Ocultas|Hidden Influences",q:"O que age sem ser visto?|What acts unseen?",why:"Posicionada antes do conselho porque o conselho depende dela.|Placed before the advice because the advice depends on it."},
      {c:4,r:1,label:"Obstáculo|Obstacle",q:"O que impede?|What stands in the way?",why:"Centro exato do arco: o ponto de maior tensão da tiragem.|The exact centre of the arc: the spread's point of greatest tension."},
      {c:5,r:1,label:"Ambiente|Environment",q:"O que os outros trazem?|What do others bring?",why:"Depois do obstáculo, porque o meio social reage ao problema, não o precede.|After the obstacle, because the social field reacts to the problem rather than preceding it."},
      {c:6,r:1,label:"Conselho|Advice",q:"Qual é a ação indicada?|What action is indicated?",why:"Penúltima: só faz sentido depois de mapeado tudo o que age.|Penultimate: it only makes sense once everything acting has been mapped."},
      {c:7,r:1,label:"Resultado|Outcome",q:"O que resulta se o conselho for seguido?|What results if the advice is followed?",why:"Ponta direita: condicionada à anterior, não independente dela.|Right end: conditioned by the previous card, not independent of it."}
    ]
  },
  {
    id:"paths", cols:5, rows:3,
    name:"Duas Estradas|Two Roads",
    use:"Decisão entre dois caminhos concretos e nomeáveis.|A decision between two concrete, nameable paths.",
    why:"A geometria é o argumento: uma raiz comum se abre em dois ramos paralelos, lidos em espelho. Compare posição por posição (2 contra 5, 3 contra 6, 4 contra 7) em vez de ler cada ramo inteiro — o contraste posicional é onde a resposta aparece. A carta 1 impede a armadilha mais comum desta tiragem: decidir sem saber o que está realmente em jogo.|The geometry is the argument: a shared root opens into two parallel branches, read in mirror. Compare position against position (2 vs 5, 3 vs 6, 4 vs 7) rather than reading each branch whole — the answer appears in the positional contrast. Card 1 blocks this spread's commonest trap: deciding without knowing what is actually at stake.",
    pos:[
      {c:1,r:2,label:"A Questão|The Question",q:"O que está verdadeiramente em jogo?|What is truly at stake?",why:"Raiz comum aos dois ramos: se esta carta contradiz a pergunta feita, a pergunta estava errada.|Root common to both branches: if this card contradicts the question asked, the question was wrong."},
      {c:2,r:1,label:"Estrada A · Se eu seguir|Road A · If I take it",q:"O que essa escolha exige?|What does this choice require?",why:"Primeiro degrau do ramo superior.|First step of the upper branch."},
      {c:3,r:1,label:"Estrada A · O que ganho|Road A · What I gain",q:"O que se abre?|What opens up?",why:"Ganho lido antes da perda, para não decidir por medo.|Gain read before loss, so the decision is not made out of fear."},
      {c:4,r:1,label:"Estrada A · O que perco|Road A · What I lose",q:"Qual o custo real?|What is the real cost?",why:"Toda escolha fecha portas; nomeá-las evita o arrependimento cego.|Every choice closes doors; naming them prevents blind regret."},
      {c:2,r:3,label:"Estrada B · Se eu seguir|Road B · If I take it",q:"O que essa escolha exige?|What does this choice require?",why:"Espelho de 2. Compare os elementos: naipes iguais indicam que as duas estradas são a mesma disfarçada.|Mirror of 2. Compare the elements: matching suits mean the two roads are the same road in disguise."},
      {c:3,r:3,label:"Estrada B · O que ganho|Road B · What I gain",q:"O que se abre?|What opens up?",why:"Espelho de 3.|Mirror of 3."},
      {c:4,r:3,label:"Estrada B · O que perco|Road B · What I lose",q:"Qual o custo real?|What is the real cost?",why:"Espelho de 4.|Mirror of 4."},
      {c:5,r:2,label:"O que nenhuma estrada resolve|What neither road solves",q:"O que continua independente da escolha?|What persists regardless of the choice?",why:"Fecha a tiragem no eixo central: quase sempre a carta mais útil, porque desinfla a decisão.|Closes the spread on the central axis: almost always the most useful card, because it deflates the decision."}
    ]
  },
  {
    id:"relation", cols:3, rows:3,
    name:"O Vínculo|The Bond",
    use:"Relação de qualquer natureza — afetiva, familiar, profissional.|A relationship of any kind — romantic, family, professional.",
    why:"Duas colunas verticais espelhadas com uma coluna central compartilhada. Cada pessoa ocupa sua própria vertical, o que impede a leitura mais comum e mais falsa em tiragens de relacionamento: atribuir a uma pessoa uma carta que descreve o campo entre as duas. Leia primeiro as colunas separadas, depois a central.|Two mirrored vertical columns with a shared central column. Each person occupies their own vertical, which blocks the commonest and falsest move in relationship readings: assigning to one person a card that describes the field between them. Read the separate columns first, then the centre.",
    pos:[
      {c:1,r:1,label:"Você · o que sente|You · what you feel",q:"Qual é o seu estado real?|What is your actual state?",why:"Alto da sua coluna: o que é consciente para você.|Top of your column: what is conscious for you."},
      {c:1,r:2,label:"Você · o que traz|You · what you bring",q:"O que você põe na relação?|What do you put into the relationship?",why:"Meio: ação, não sentimento.|Middle: action, not feeling."},
      {c:1,r:3,label:"Você · o que esconde|You · what you withhold",q:"O que não está dito do seu lado?|What is unspoken on your side?",why:"Base: o inconsciente da sua coluna, sustentando as outras duas.|Base: your column's unconscious, holding up the other two."},
      {c:3,r:1,label:"O outro · o que sente|The other · what they feel",q:"Qual é o estado real do outro?|What is their actual state?",why:"Espelho. Trate como hipótese de leitura, nunca como fato sobre outra pessoa.|Mirror. Treat as a reading hypothesis, never as fact about another person."},
      {c:3,r:2,label:"O outro · o que traz|The other · what they bring",q:"O que a outra pessoa põe?|What do they put in?",why:"Espelho da posição 2.|Mirror of position 2."},
      {c:3,r:3,label:"O outro · o que esconde|The other · what they withhold",q:"O que não está dito do lado dele?|What is unspoken on their side?",why:"Espelho da posição 3.|Mirror of position 3."},
      {c:2,r:1,label:"O que existe entre|What exists between",q:"Qual é a natureza do campo?|What is the nature of the field?",why:"Coluna central: pertence a ninguém e aos dois.|Central column: it belongs to neither and to both."},
      {c:2,r:2,label:"O ponto de atrito|The friction point",q:"Onde isso trava?|Where does it jam?",why:"Centro exato: cruzamento das duas verticais.|Exact centre: the crossing of both verticals."},
      {c:2,r:3,label:"O que o vínculo pede|What the bond asks",q:"O que a relação pede para seguir?|What does the relationship require to continue?",why:"Base do eixo comum: fundação da relação, não desejo de nenhum dos dois.|Base of the shared axis: the relationship's foundation, not either person's wish."}
    ]
  },
  {
    id:"tree", cols:3, rows:8,
    name:"Árvore da Vida|Tree of Life",
    use:"Retrato completo de um momento de vida, em profundidade cabalística.|A complete portrait of a life moment, in Kabbalistic depth.",
    why:"Dez posições sobre as Sephiroth, mais Daath (o abismo) como carta opcional. A geometria não é decorativa: as três colunas são Rigor (esquerda), Misericórdia (direita) e Equilíbrio (centro), e a leitura desce de Kether a Malkuth — do abstrato ao concreto. Uma sobrecarga de cartas numa das colunas laterais é, por si só, o diagnóstico. Pollack descreve uma versão com o baralho inteiro distribuído em dez montes; esta é a redução de uma carta por Sephirah, viável para leitura fotográfica.|Ten positions on the Sephiroth, plus Daath (the abyss) as an optional card. The geometry is not decorative: the three columns are Severity (left), Mercy (right) and Balance (centre), and the reading descends from Kether to Malkuth — abstract to concrete. An overload of cards in one side column is itself the diagnosis. Pollack describes a version using the whole deck dealt into ten piles; this is the one-card-per-Sephirah reduction, viable for photographic reading.",
    pos:[
      {c:2,r:1,label:"1 · Kether · Propósito|1 · Kether · Purpose",q:"Qual é a fonte disso?|What is the source of this?",why:"Topo do pilar central: a intenção antes de qualquer forma.|Top of the central pillar: intention before any form."},
      {c:3,r:2,label:"2 · Chokmah · Impulso|2 · Chokmah · Impulse",q:"Que força criativa está agindo?|What creative force is at work?",why:"Alto do pilar da Misericórdia: expansão pura.|Top of the Mercy pillar: pure expansion."},
      {c:1,r:2,label:"3 · Binah · Forma|3 · Binah · Form",q:"Que estrutura está sendo dada?|What structure is being given?",why:"Alto do pilar do Rigor: o limite que torna o impulso real.|Top of the Severity pillar: the limit that makes impulse real."},
      {c:2,r:3,label:"Daath · O Abismo|Daath · The Abyss",q:"O que foi negado ou esquecido?|What has been denied or forgotten?",why:"Sephirah não-Sephirah. Opcional; quando incluída, costuma ser a carta mais dura da tiragem.|The non-Sephirah. Optional; when included it is usually the harshest card of the spread.",opt:true},
      {c:3,r:4,label:"4 · Chesed · Expansão|4 · Chesed · Expansion",q:"Onde há crescimento?|Where is there growth?",why:"Misericórdia manifesta.|Mercy made manifest."},
      {c:1,r:4,label:"5 · Geburah · Corte|5 · Geburah · Severance",q:"O que precisa ser cortado?|What needs to be cut?",why:"Rigor manifesto: o par que impede Chesed de virar excesso.|Severity made manifest: the pair that keeps Chesed from becoming excess."},
      {c:2,r:5,label:"6 · Tiphareth · Coração|6 · Tiphareth · Heart",q:"Qual é o centro consciente?|What is the conscious centre?",why:"Meio exato da Árvore: recebe de todas as Sephiroth acima. Se a leitura tiver um eixo, está aqui.|Exact middle of the Tree: it receives from every Sephirah above. If the reading has an axis, it is here.",key:true},
      {c:3,r:6,label:"7 · Netzach · Desejo|7 · Netzach · Desire",q:"O que atrai?|What attracts?",why:"Emoção e apetite, no pilar da expansão.|Emotion and appetite, on the expansive pillar."},
      {c:1,r:6,label:"8 · Hod · Razão|8 · Hod · Reason",q:"O que a mente diz?|What does the mind say?",why:"Intelecto, no pilar da forma. Leia sempre contra 7.|Intellect, on the pillar of form. Always read it against 7."},
      {c:2,r:7,label:"9 · Yesod · Fundamento|9 · Yesod · Foundation",q:"O que o inconsciente sustenta?|What does the unconscious hold up?",why:"Última estação antes do mundo material.|The last station before the material world."},
      {c:2,r:8,label:"10 · Malkuth · Manifestação|10 · Malkuth · Manifestation",q:"Como isso aparece na vida concreta?|How does this show up in concrete life?",why:"Base: o resultado tangível de tudo acima.|Base: the tangible result of everything above."}
    ]
  },
  {
    id:"cycle", cols:0, rows:0, open:true,
    name:"Ciclo de Trabalho|Work Cycle",
    use:"Leitura aberta, longa, sem posições fixas — para um processo em andamento.|An open, long reading with no fixed positions — for a process underway.",
    why:"Descrita por Pollack: nove ou mais cartas dispostas em linhas, sem posições atribuídas. O sentido não vem de onde a carta caiu, mas de como o conjunto se organiza — quais naipes dominam, quais faltam, onde os Arcanos Maiores se agrupam, quais cartas-portal aparecem. É a tiragem que mais exige do leitor e a que menos permite automatismo, porque não há posição para se apoiar. Use quando a pergunta não couber numa forma.|Described by Pollack: nine or more cards laid in rows, with no assigned positions. Meaning comes not from where a card fell but from how the whole organises — which suits dominate, which are missing, where the Majors cluster, which portal cards appear. It is the spread that demands most of the reader and permits least automatism, because there is no position to lean on. Use it when the question will not fit a shape.",
    pos:[]
  }
];

/* ---------- CAMADA METODOLÓGICA ---------- */

const DIGNITY = {
  Fire:{ same:"Fire", enemy:"Water", friend:["Air","Earth"] },
  Water:{ same:"Water", enemy:"Fire", friend:["Air","Earth"] },
  Air:{ same:"Air", enemy:"Earth", friend:["Fire","Water"] },
  Earth:{ same:"Earth", enemy:"Air", friend:["Fire","Water"] },
};
const dignityOf = (a, b) => {
  if (!a || !b) return null;
  if (a === b) return "same";
  if (DIGNITY[a].enemy === b) return "enemy";
  return "friend";
};

const METHOD = [
  { id:"dign", t:"Dignidades Elementais|Elemental Dignities",
    b:"Descrita por MacGregor Mathers no 'Book T' da Golden Dawn. Cartas vizinhas modificam a força umas das outras — não o sentido, a intensidade. Mesmo elemento: reforço forte, para o bem ou para o mal. Fogo/Água e Ar/Terra: inimigos, enfraquecem-se muito. Todo o resto (Fogo/Ar, Fogo/Terra, Água/Ar, Água/Terra): amigável.\n\nTENSÃO A NOMEAR: o Golden Dawn original tinha apenas TRÊS categorias — reforça muito, enfraquece muito, amigável. Boa parte do material popular contemporâneo acrescentou uma quarta categoria, 'neutro', aplicada a Fogo/Terra e Ar/Água. Mary K. Greer e Anthony Louis, que trabalharam sobre o texto de Mathers, sustentam que 'amigável' nunca significou 'neutro'. O app usa o esquema original de três categorias e assinala quando a leitura tocaria essa divergência.\n\nREGRAS DE TRÍADE (Mathers, verificadas em duas fontes independentes): se as duas cartas laterais forem contrárias à central, dominam-na e ela fica muito fraca. Se as laterais forem contrárias ENTRE SI, anulam-se e a carta central lê-se como se estivesse sozinha. Se apenas uma lateral for contrária, a outra funciona como ponte e a central permanece razoavelmente forte.|Described by MacGregor Mathers in the Golden Dawn's 'Book T'. Neighbouring cards modify each other's strength — not the meaning, the intensity. Same element: strong reinforcement, for good or ill. Fire/Water and Air/Earth: enemies, greatly weakening. Everything else (Fire/Air, Fire/Earth, Water/Air, Water/Earth): friendly.\n\nTENSION TO NAME: the original Golden Dawn had only THREE categories — greatly strengthening, greatly weakening, friendly. Much popular contemporary material added a fourth, 'neutral', applied to Fire/Earth and Air/Water. Mary K. Greer and Anthony Louis, working from Mathers' text, hold that 'friendly' never meant 'neutral'. This app uses the original three-category scheme and flags where a reading would touch that divergence.\n\nTRIAD RULES (Mathers, verified in two independent sources): if both flanking cards are contrary to the centre, they dominate it and it becomes very weak. If the flanking cards are contrary TO EACH OTHER, they cancel and the centre card reads as though alone. If only one flank is contrary, the other acts as a bridge and the centre stays reasonably strong." },
  { id:"absence", t:"Ausência de Naipe|Suit Absence",
    b:"A ausência de um naipe numa tiragem é um dado tão interpretável quanto qualquer carta presente. Sem Espadas: a questão não está sendo pensada, só sentida ou agida. Sem Copas: o afeto foi excluído do cálculo. Sem Paus: falta impulso, não falta clareza. Sem Ouros: a questão não tem ancoragem material — pode ser bonita e irrealizável. Excesso de Arcanos Maiores indica que a situação escapou ao controle pessoal; excesso de Menores, que ela é mais mundana do que a pergunta sugeria.|The absence of a suit in a spread is as interpretable as any card present. No Swords: the question is not being thought, only felt or acted. No Cups: feeling has been excluded from the calculation. No Wands: impulse is missing, not clarity. No Pentacles: the question has no material anchor — it may be beautiful and unrealisable. An excess of Majors indicates the situation has slipped beyond personal control; an excess of Minors, that it is more mundane than the question implied." },
  { id:"portal", t:"Cartas-Portal|Portal Cards",
    b:"Conceito de Pollack: certas cartas abrem experiência arquetípica além do seu sentido literal, geralmente por conterem uma figura de costas, um limiar, ou um padrão que replica a estrutura do próprio Tarô. Neste baralho: Três de Paus, Oito de Copas, Seis de Espadas, Seis de Ouros, Nove de Ouros, Dez de Ouros. Quando uma delas cai, a leitura muda de registro — deixa de descrever a situação e passa a descrever a posição do consulente diante dela.|Pollack's concept: certain cards open archetypal experience beyond their literal sense, usually by containing a figure seen from behind, a threshold, or a pattern replicating the structure of the Tarot itself. In this deck: Three of Wands, Eight of Cups, Six of Swords, Six of Pentacles, Nine of Pentacles, Ten of Pentacles. When one falls, the reading changes register — it stops describing the situation and begins describing the querent's position before it." },
  { id:"jumper", t:"Cartas Saltadoras|Jumper Cards",
    b:"Cartas que saem espontaneamente do baralho durante o embaralhamento têm peso interpretativo amplificado. A emergência não solicitada intensifica a mensagem — a carta não foi escolhida por posição nem por contagem, apareceu. Detalhes físicos importam e são tratados como extensão simbólica: o arco da queda, a posição final, se colidiu com outra carta. Registre a saltadora no campo de contexto para que ela entre na leitura com esse peso.|Cards that fall spontaneously from the deck during shuffling carry amplified interpretive weight. Unsolicited emergence intensifies the message — the card was chosen by neither position nor count; it appeared. Physical details matter and are treated as symbolic extension: the arc of the fall, the final position, whether it struck another card. Record the jumper in the context field so it enters the reading with that weight." },
  { id:"lines", t:"As Três Linhas de Pollack|Pollack's Three Lines",
    b:"O Louco (0) fica sozinho, fora e antes. Os 21 Maiores restantes formam três linhas de sete.\nLINHA 1 (1–7, Mago a Carro): o mundo exterior, a maturação do ego, o que se aprende para funcionar socialmente.\nLINHA 2 (8–14, Força a Temperança): a busca interior, o descenso ao subconsciente, o encontro com o que o ego construiu e não sabe sustentar.\nLINHA 3 (15–21, Diabo a Mundo): o superconsciente, a união arquetípica, forças maiores que a biografia pessoal.\nPADRÃO DOS QUATRO: Louco–Mago–Sacerdotisa–Mundo = potencialidade, dualidade, unidade. Quando Maiores dominam uma tiragem, localizar em que linha se agrupam diz em que fase do arco o consulente está.|The Fool (0) stands alone, outside and before. The remaining 21 Majors form three lines of seven.\nLINE 1 (1–7, Magician to Chariot): the outer world, the ego's maturation, what is learned in order to function socially.\nLINE 2 (8–14, Strength to Temperance): the inward search, the descent into the subconscious, meeting what the ego built and cannot sustain.\nLINE 3 (15–21, Devil to World): the superconscious, archetypal union, forces larger than personal biography.\nPATTERN OF FOUR: Fool–Magician–High Priestess–World = potentiality, duality, unity. When Majors dominate a spread, locating which line they cluster in tells you which phase of the arc the querent is in." },
  { id:"rev", t:"Reversões|Reversals",
    b:"Em Pollack, uma carta invertida não é o oposto da carta direita: é a mesma energia bloqueada, adiada, voltada para dentro, ou recanalizada. O Sol invertido não é escuridão — é luz que não está sendo deixada entrar.\n\nPROTOCOLO: uma carta só é lida como invertida mediante confirmação explícita. Se a mão inteira foi embaralhada invertida, a inversão de uma carta individual deixa de ser metodologicamente significativa e o app levanta essa questão em vez de decidir por você.|In Pollack, a reversed card is not the opposite of the upright: it is the same energy blocked, delayed, turned inward, or rechannelled. The Sun reversed is not darkness — it is light not being let in.\n\nPROTOCOL: a card is read as reversed only on explicit confirmation. If the whole hand was shuffled reversed, an individual card's inversion ceases to be methodologically meaningful and the app raises that question rather than deciding for you." },
  { id:"combo", t:"Combinações|Combinations",
    b:"Ler combinações é ler conversa, não somar significados. Quatro operações:\n1. REFORÇO — mesmo naipe ou mesmo número: o tema é sublinhado. Números repetidos são um dos sinais mais fortes do baralho (três Cincos = crise em três frentes).\n2. CONTRADIÇÃO — cartas que se opõem: o consulente está dividido, e o conflito é a mensagem, não um erro da tiragem.\n3. SEQUÊNCIA — cartas que contam uma ordem: A leva a B leva a C.\n4. QUALIFICAÇÃO — uma carta modifica o tom da outra sem mudar seu sentido. Oito de Ouros + Força = prática paciente; Oito de Ouros + Diabo = trabalho tornado compulsão. A primeira carta não mudou.\nRepetições visuais (a mesma cor, o mesmo gesto, a mesma criatura em várias cartas) são leitura legítima e frequentemente mais precisa do que a soma dos significados.|Reading combinations is reading conversation, not adding meanings. Four operations:\n1. REINFORCEMENT — same suit or same number: the theme is underlined. Repeated numbers are one of the deck's strongest signals (three Fives = crisis on three fronts).\n2. CONTRADICTION — cards that oppose: the querent is divided, and the conflict is the message, not a fault in the spread.\n3. SEQUENCE — cards telling an order: A leads to B leads to C.\n4. QUALIFICATION — one card modifies another's tone without changing its sense. Eight of Pentacles + Strength = patient practice; Eight of Pentacles + Devil = work become compulsion. The first card has not changed.\nVisual repetitions (the same colour, gesture, or creature across cards) are legitimate reading and often more precise than the sum of meanings." },
  { id:"phil", t:"Filosofia Divinatória|Divinatory Philosophy",
    b:"As cartas não determinam destino. Elas refletem condicionamento somado a resultado provável: o que tende a acontecer se nada mudar. O livre-arbítrio existe e raramente é exercido — é por isso que as previsões funcionam com a frequência que funcionam, e não porque o futuro esteja escrito.\n\nNenhuma carta é boa ou má em si. O contexto determina o significado: a Torre numa pergunta sobre uma estrutura que já não serve é alívio; numa pergunta sobre uma casa recém-comprada, é outra coisa. A posição, a pergunta e as vizinhas fazem o sentido — a carta sozinha só oferece o material.|The cards do not determine fate. They reflect conditioning plus likely outcome: what tends to happen if nothing changes. Free will exists and is rarely exercised — which is why predictions work as often as they do, not because the future is written.\n\nNo card is good or bad in itself. Context determines meaning: the Tower in a question about a structure that no longer serves is relief; in a question about a newly bought house, it is something else. Position, question and neighbours make the sense — the card alone only supplies the material." },
];


export { SPREADS, DIGNITY, dignityOf, METHOD };
